### ISSUE TITLE
Bin-files delete

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#100]
I created a new branch from master and had no /bin-files to run my app.

Someone has put them under version control, I do not know why we have to do this or if something has changed. But I had to run ```rake rails:update```and say No to changing all our config files.

It also added a few new files which must be from upgrading Rails, so I'll put them on my PR for #99.

Question: Should we VS ```/bin```?

**Comment by Zofz** [comment]
Issue #100, wohoo ;)

**Comment by henrikssn** [comment]
We need our capistrano binary `bin/cap`, otherwise our deployments need a bundle install from scratch which takes about 10 mins...

The rest of them should not be checked in.

**Comment by davidwessman** [comment]
Okey, then we should edit the ```.gitignore``` to just version-check the ```capistrano```bin.
Can you fix this?

**Comment by davidwessman** [comment]
"...This will generate a bin directory in the root of your application. Make sure that it is not in your .gitignore file, and check this directory and its contents into git."

This ref is mostly about Heroku, but why shouldn't they be version-controlled?

Ref:
https://devcenter.heroku.com/articles/rails4

**Comment by henrikssn** [comment]
I think you are right here. We should check them in.

*"You are encouraged to check these binstubs in the project's version control so your colleagues might benefit from them."*

https://github.com/sstephenson/rbenv/wiki/Understanding-binstubs

**Comment by davidwessman** [comment]
Can you edit the .gitignore in #101 and merge?

**Comment by davidwessman** [comment]
Closed by #101

**Comment by davidwessman** [comment]
Closed by #101
