### ISSUE TITLE
Non-confirmed meeting requests email

### ISSUE THREAD

**Issue by FredrikLastow** [fsek/web#1003]
Now a mail is sent to the president which is not super good. Instead we would like to change it to the "prylmästare".

**Comment by Lullebullelukas** [comment]
This should be fixed now that I changed the mail alias lokalbokning@fsektionen.se to go to prylm@fsektionen.se (it was linked to ordf@fsektionen.se), the mail lokalbokning@fsektionen.se is hard coded in our meetingmailer
