### ISSUE TITLE
Updates to tool-lending system

### ISSUE THREAD

**Issue by KingJohanna** [fsek/web#1035]
- Entering the name of the lender should yield a list of users on the website, so the tool is then connected to a user instead of simply a name (like when renting the car).
- Make (the name of the) lender only visible to admins.
- If the set return date has been passed without the tool being returned, the lender and prylmästare (and fixare) should be sent a reminder/warning message/e-mail.
- The date the tool was lent should be saved and displayed.
- DIsplay the number of available tools as [# of available tools] / [# of total tools]

**Comment by ldrenth** [comment]
Closed by #1057
