### ISSUE TITLE
Confusion between User and Profile

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#105]
I am very confused regarding these two models. Why do we have both?

**Comment by jforberg** [comment]
Yes they should be merged! They are two classes representing the same thing.

**Comment by jforberg** [comment]
I claim this task!

**Comment by henrikssn** [comment]
Bonus point if you merge profile into user :+1:

**Comment by jforberg** [comment]
Migrations ftw

**Comment by davidwessman** [comment]
I have long wondered why it was set up like this, but is there any reason to keep them apart?

**Comment by henrikssn** [comment]
No.

**Comment by davidwessman** [comment]
(y)

**Comment by jforberg** [comment]
The only thing we do is open up the possibility for conflicts.

Like we have users.email and profiles.email... This is a common error to make, thankfully it's easy to fix using a little sql-fu.

**Comment by jforberg** [comment]
I've written the migration. Unfortunately the Profile code is very coupled and we have mentions of profile all over the place.

https://github.com/fsek/web/blob/profile-merge/db/migrate/20410822171446_merge_profile_into_user.rb

Now I need your help @henrikssn @davidwessman etc. to port our code to the new system.

Do note once you run my migration you will have to db:reset to get back to the master schema. This will clear out the contents of your database so make a dump first or something.

Also we have the problem of https://github.com/fsek/web/issues/108 that will f*** up our migrations in the future, maybe this is the right time to fix it.

**Comment by jforberg** [comment]
Also note that Mysql doesn't support transactions for structural changes so if you run into an error your migration will fail and leave the database broken. So unless you have some data in your database that you care about (which you shouldn't have anyway) it would be better to just db:schema:load.

I'll be hand-holding the migration when we deploy to production.

**Comment by davidwessman** [comment]
Should we turn it into a PR and work from there?

**Comment by jforberg** [comment]
Yes. https://github.com/fsek/web/pull/109

**Comment by lham** [comment]
Det var jag som gjorde det designvalet när vi startade upp projektet. Anledningen är att jag gillar att separera "inloggningssystem" från en "fysisk person/profil". Detta för att förenkla processen om man t.ex. byter ut user-systemet mot t.ex. ldap eller kårens medlemsregister. Visst, det går att göra med samma tabell/model, men jag gillar den abstrakta separationen mellan de två entiteterna.

Jag kommer inte motsätta mig mot att ni ändrar det men ovan är fortfarande min ståndpunkt.

**Comment by jforberg** [comment]
@lham Jag har i princip inget emot att det finns två olika tabeller för ett koncept. Idag duplicerar vi dock email etc. vilket jag inte tyckdavidwessmaner är bra. Vi hade precis samma design på Lundakarnevalen och det ledde till problem som hade kunnat undvikas (i just det fallet).

Här tycker jag det är viktigast att tänka konceptuellt. Går det att tänka sig ett scenario där en profile inte hänger ihop med en user eller är det faktiskt samma sak?

**Comment by davidwessman** [comment]
```... tyckdavidwessmanner...```;) 
Duplicerade epostfält är mitt fel, men jag har inte viljat ändra så mycket i user heller.

**Comment by lham** [comment]
@jforberg Nä, en förutsättning är ju att man undviker duplikation, det leder aldrig till något gott. Att jag råkade lägga till det har jag svårt att tänka mig (även om disträ är en egenskap jag besitter), men kan ta på mig skulden för förvirring i koden i alla fall! ;) 

I vårt fall har jag svårt att se att de skulle gå att separera (dvs att det skulle finnas ett scenario där vi vill ha en profil utan user och vice versa). Men som sagt, jag tycker där finns en skillnad mellan dem och jag tycker inte att man måste slå ihop dem bara för att de är oseparerbara.

**Comment by davidwessman** [comment]
hur ställer vi oss till detta nu? vad tycker alla?

**Comment by henrikssn** [comment]
Jag anser att de är samma sak och bör sättas ihop till en modell.

@lham Om det inte finns något tillfälle då man vill ha en User utan profile (eller tvärtom) så ska de vara i samma modell. Annars får vi massa overhead då vi måste kontrollera att varje user har en profile och att varje profile har en user. Vad händer om create_profile failar efter att en user skapats? Troligen massa fel överallt då alla modeller förutsätter att varje user har en profile.

Vill vi trasha vårt inloggningssystem till fördel för LDAP/nått annat i framtiden så gör det inte någonting att det ligger några extra fields i User(/Profile) som vi inte behöver. Dessa kan ju också enkelt tas bort med en migration.

**Comment by jforberg** [comment]
+1 merge. Jag förstår @lham resonemang men min erfarenhet när vi gjort precis samma sak på samma ställen är att det orsakar problem i form av sena supportsamtal... Bevisligen är vi förvirrade eftersom vi redan börjat duplicera data mellan modellerna.

**Comment by jforberg** [comment]
FYI har 14% av våra användare olika mailadress på sin profile och sin user...

**Comment by davidwessman** [comment]
Simplicity är ju alltid fett - det var en viss styrelsemedlem som hade två konton på hemsidan, båda hade omvänt använt två mailadresser. Det tog lite tid att förstå vad som hände där... ;) 

+1 merge.

**Comment by davidwessman** [comment]
Almost done? ;) @fsek/admins
