### ISSUE TITLE
Tests are broken on master

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#106]
https://travis-ci.org/fsek/web/builds/55516080

@jforberg Fix asap please

**Comment by jforberg** [comment]
Can not reproduce.

**Comment by jforberg** [comment]
Note they have

``export DB=sqlite``

In their printout. Our deployment database is mysql. Don't know if this would affect, probably not.

**Comment by jforberg** [comment]
Also they run Ruby 2.2.0 which is an outdated version. The current stable version is 2.2.1

**Comment by henrikssn** [comment]
It fails for me locally both with 2.1.4 and 2.2.0. Travis runs ruby 2.2.0 because that is what we run on the production server.

**Comment by henrikssn** [comment]
Comment the test or something until you have a fix, deploy pipeline is currently stalled because of this.

**Comment by jforberg** [comment]
I think I know what it is. Trying now.

**Comment by jforberg** [comment]
Yes. It was a bug in my tests, strange that they passed on my machine...
