### ISSUE TITLE
Redirect Warning in app/controllers/short_links_controller.rb

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#107]
[Security issue from Hakiri](https://hakiri.io/projects/1bba4e49152bac/stacks/656e52150d745c/builds/89fe33e064f0b4/warnings/7c6f80c153ac33): Possible unprotected redirect in app/controllers/short_links_controller.rb

Are we sure that this is safe?

**Comment by davidwessman** [comment]
@jforberg

**Comment by jforberg** [comment]
Vad är det den klagar på? Länken ger mig 404.

Låt oss gissa att den klagar på att jag redirectar till en url-sträng. Och nej, det är ju inte garanterat säkert men om vi inte litar på vår admins att skriva in icke-ondskefulla adresser så faller ju hela konceptet.

**Comment by jforberg** [comment]
Detta är en false positive. Om någon som har access till hakiri vill markera den så vore det topp.

**Comment by henrikssn** [comment]
Fixat
