### ISSUE TITLE
Fel versionering av migrationer

### ISSUE THREAD

**Issue by jforberg** [fsek/web#108]
Vår ActiveRecord är felkonfad. Någon har råkat ställa den så att den versionerar sina migrationer med enkelt stigande (skitstora) tal:

``ActiveRecord::Schema.define(version: 20410822171446) do``

och nästa

``ActiveRecord::Schema.define(version: 20410822171447) do``

Detta är inte så bra. Migrationer ska numreras med datumstämplar ner till sekundtal så att man vet i vilken ordning de kommer. Annars får vi problem när vi ska merga eftersom vi kommer ha två migrations med samma nummer.

Detta medför dubbel huvudvärk eftersom nuvarande migrations behöver numreras om... Både i databasen och i koden.

**Comment by jforberg** [comment]
Förslagsvis löser vi detta genom att fälla ihop alla tidigare migrations i en stor migration som får bli Migration Nummer Noll. Sedan lite SQL-kod som droppar alla värden i tabellen schema_migrations.

**Comment by henrikssn** [comment]
Har också tänkt på detta. Låter bra :+1:

**Comment by davidwessman** [comment]
Detta borde vi köra ut så snabbt som möjligt - hur tungt är det?
För allt vi implementerar och vill få ut kommer ju bli mer och mer problem.

**Comment by jforberg** [comment]
Det är lätt men behöver tajmas med andra ändringar. Jag tittar på det vid tillfälle.

**Comment by henrikssn** [comment]
#144
