### ISSUE TITLE
Admin-menyn försvinner utanför fönstret

### ISSUE THREAD

**Issue by jforberg** [fsek/web#113]
Adminmenyn anpassar sig inte efter skärmstorleken utan försvinner för små skärmar.

![2015-03-24-231816_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1269005/6814255/43ebe690-d27d-11e4-846a-8c3d2ab104f4.png)

Om vi nu tillåter oss att definiera ett fönster på nästan 1000px som litet.

Inte ens i 1080p blir det superbra.

![2015-03-24-231820_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1269005/6814264/537a2bda-d27d-11e4-8277-8b2592bd6226.png)

Någon som är lite påläst på layouten kanske vill titta på detta.

**Comment by jforberg** [comment]
Det ska tilläggas att jag kör med 125% zoom.

**Comment by davidwessman** [comment]
@lham har rätt bra koll på Bootstrap + Unify?

**Comment by davidwessman** [comment]
This works better on desktop now but not that good on phones.

**Comment by davidwessman** [comment]
Now it should work better on phones as well.
