### ISSUE TITLE
[Production]: Kan inte visa/redigera/skapa utskott

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#118]
HTTP 500 http://fsektionen.se/utskott

**Comment by davidwessman** [comment]
Noticed this, anyone who can check out the log? Do not have access to a terminal.

**Comment by henrikssn** [comment]
```app/views/layouts/_utskottmenu.html.erb:4: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...link_to u.title, council_path u );@output_buffer.safe_append...
...                               ^):
  app/views/layouts/_utskottmenu.html.erb:4: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
  app/views/layouts/application.html.erb:90:in '_app_views_layouts_application_html_erb___2158310572239716173_70342967545060' ```

**Comment by davidwessman** [comment]
https://github.com/fsek/web/blob/cd92aa626f1ba43c7c809f84e50329279ead6054/app/views/layouts/_utskottmenu.html.erb
seems to be the '''council_path u''' that should be council_path(u). @jforberg?

**Comment by jforberg** [comment]
This is my fault. Fix now in 7a2febb7e1f6e31e1dcd8669b6bb4987b24aa504

**Comment by henrikssn** [comment]
I am quite amazed how our tests cannot have catched this. We should add a test so it doesn't happen again.

**Comment by davidwessman** [comment]
We do not have tests for everything yet? ;)

**Comment by henrikssn** [comment]
We should at least verify we get http 200 for all #index paths in routes.rb. This should be a quite quick and fast test to write.

**Comment by henrikssn** [comment]
@jforberg Nu funkar index men inte #show http://fsektionen.se/utskott/kultur

**Comment by jforberg** [comment]
Detta beror delvis på att många saker är svåra att testa utan testdata. Därför: https://github.com/fsek/web/issues/121

**Comment by henrikssn** [comment]
@jforberg Vi behöver inga testdata för att köra GET /utskott

Jag gjorde ett snabbt test i e7ebd207 som testar just detta för de paths jag kunde komma på.

**Comment by jforberg** [comment]
@henrikssn Jag kanske är otydlig, menar inte test som i rspec utan test som i "slå upp appen i min webbläsare, bråka lite med den och se vad som händer". Vilket är hur jag brukar utveckla viewar.

**Comment by davidwessman** [comment]
Men i detta fallet så kördes ju inte den felaktiga koden om det inte fanns några utskott.
En populated-databas gör översikten lättare.

**Comment by henrikssn** [comment]
@jforberg Det testet jag skrev gör just det.

Starta hela rails, simulera webbläsare, gå till /utskott och verifiera att status code är 200 OK.

@davidwessman Ja, hade databasen varit seedad hade vi även kunnat besöka /utskott/1 :)

**Comment by jforberg** [comment]
Fix the other reg-bug 07576495409f6a8e0a26f1e7a2eb2971f35df4d1
