### ISSUE TITLE
Foreign keys must end with _id

### ISSUE THREAD

**Issue by jforberg** [fsek/web#119]
When you have a foreign key in your table (e.g. users.profile_id) then it is **very important** that it ends with _id.

Why? Because otherwise they take up the name that should be used for the association.

Let's take an example from our codebase:

```
mysql> describe councils;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| president         | int(11)      | YES  |     | NULL    |                |
```

Do you see the problem? Then we have to do something silly like

```
class Council
  has_one :president_assoc, :class_name => :Profile, :foreign_key => :president
...

council.pressident_assoc
```

Or even worse (this makes eager loading impossible).

```
president = Profile.find_by_id council.president
```

When we would like to just say

```
class Council
  has_one :president, :class_name => :Profile

council.president
```

This is one of many cases where it's just not worth it to fight against the framework. 

Therefore, we should move all our foreign key so that they are named assoc_id where assoc is the name of the association.

**Comment by henrikssn** [comment]
:+1:

**Comment by davidwessman** [comment]
Yeap, that one is on me as well ;) 

What you will constantly see in the code (the not refactored part, hopefully) is me trying to ```learn``` Rails.
So there will be these kind off screw ups all the way through the code.

I do hope that what I am working on now is getting better and better.

**Comment by jforberg** [comment]
@davidwessman No problem, learning rails well takes a very long time. There is a great deal to learn. I'm just trying to give my view on things that have bitten me in the past, hopefully in a tempo where you feel like you can follow along.

"No one writes perfect code the first time around. Well, except me, but there's only one of me." 
-- Linus T.

**Comment by davidwessman** [comment]
😄 I can definitely see that but I can feel it changing now when there is actually someone to discuss code with and that can review changes - it's great! 😄 :+1:

**Comment by davidwessman** [comment]
@fsek/admins Should we try to structure up a Wiki?
This posts is perfect there and we do not want to close this issue and hide for ever.

**Comment by henrikssn** [comment]
@davidwessman You can move this to the wiki and then close

**Comment by davidwessman** [comment]
Created Wiki-page:
https://github.com/fsek/web/wiki/Foreign-keys-must-end-with-_id
