### ISSUE TITLE
Test: http 200 for all #index paths in routes.rb.

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#120]
#118

**Comment by jforberg** [comment]
Good. Remember to ``render_views`` in your tests, otherwise the views are ignored.

**Comment by henrikssn** [comment]
e7ebd207

Will fix a logged_on version later

**Comment by davidwessman** [comment]
Fixed in #109.
Check out:
https://github.com/fsek/web/blob/master/spec/features/admin_visit_spec.rb
