### ISSUE TITLE
Put together a nice test database

### ISSUE THREAD

**Issue by jforberg** [fsek/web#121]
We need a collection of test data for our personal development databases. It's too tedious to populate it manually and for development we often have to nuke the DB anyway.

Ideally you would say

```
rake db:fill_with_stuff
```

And you would get a database filled with realistic data.

This is not hard to do, a good task for someone who wants to learn about rake. A tip is to start from the live production database and dump attributes from there.

**Comment by henrikssn** [comment]
You mean db/seeds.rb? ;)

**Comment by jforberg** [comment]
@henrikssn Maybe.

The way I see it, seeds.rb is the **minimum** viable contents of the database, containing just the data the app needs to work. Maybe you see it differently.

What I'm looking for is just a random collection of data that looks similar to the data in the production database.

**Comment by davidwessman** [comment]
We could use our Factories for this perhaps?

And whenever i run rspec locally, my DB is ```nuked```, I haven't really had the time to look at it properly.

**Comment by henrikssn** [comment]
@jforberg Your're right. We should not use seeds.rb for this

Maybe add a helper file which seeds the database and then include that in the tests which want a seeded database?

**Comment by jforberg** [comment]
@henrikssn Maybe. Again, I'm talking about "tests" as in just running the app in dev mode.

For now I'll just use plain SQL dumps but I can't check those into the git because they contain password hashes etc.

**Comment by henrikssn** [comment]
Oh, I see. My dev database is quite "seeded" so I do not have that problem :)

But this is a problem for the feature tests (which run in a simulated web browser) too. We should have tests like:
* Register user, verify we can log in, go to random site and verify random stuff

**Comment by davidwessman** [comment]
If we keep on building on https://github.com/fsek/web/blob/master/lib/tasks/tests_data.rake 
this is solved? 😄

**Comment by henrikssn** [comment]
Haha lol I just created a PR for this

**Comment by davidwessman** [comment]
Haha ;) this is already deployed  - so I'm a head of you ;)

**Comment by davidwessman** [comment]
Do you people still think this is an issue?
We have a https://github.com/fsek/web/blob/master/lib/tasks/tests_data.rake
It could do with a better name, and perhaps adding more models. But this is more like development than an actual issue, or is there another solution for this?

**Comment by jforberg** [comment]
@davidwessman That looks like just what I wanted. Good work.

**Comment by davidwessman** [comment]
Remember to add here anytime you want to test something new on the site, so that the next person can use it as well 😄
