### ISSUE TITLE
Mass Assignment Warning in app/controllers/proposals_controller.rb

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#122]
[Security issue from Hakiri](https://hakiri.io/projects/1bba4e49152bac/stacks/656e52150d745c/builds/9ebf93f2b44211/warnings/d398b23e663578): Parameters should be whitelisted for mass assignment in app/controllers/proposals_controller.rb

I think this was introduced in #114

**Comment by henrikssn** [comment]
Den vill att du ska explicit whitelista dina params med permit så vi inte tillåter vad som helst.

**Comment by jforberg** [comment]
Eftersom objektet aldrig rör databasen tyckte jag att det inte var nödvändigt. Men jag kan göra det för tydlighetens skull.
