### ISSUE TITLE
Vårterminsmötet: voting

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#124]
The board asked what we think about a voting system ready for the 21st of april.

What would it require?
- Check in, users' IDs must be checked and they must be checked in to be able to vote.
- Setting up different votes for different questions.
- Need to allow Multiple-choice and Yes/No
- Need to be able to check the result properly.

I am quite sceptic, the deadline is kind of short (since we have a lot of issues+features coming up) and the system is very vulnerable and seems a bit unsafe.

What do you guys think?

**Comment by jforberg** [comment]
No. We don not want to be responsible for this. If you decide to do this then best of luck but I won't have any part in it :) in fact you should probably revoke my root access during the meeting.

If you really think you need a digital voting system, then use a production system like http://www.voteit.se/ which is currently the best open source voting system in Sweden. But I've used that system and it's not worth the trouble.

Digital voting is like drugs. Just say no.

**Comment by henrikssn** [comment]
No, I do not feel confident doing this.

**Comment by davidwessman** [comment]
Good, then we do all agree, I will forward this.
