### ISSUE TITLE
Permission: User

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#126]
Should not be included for Posts - right?

Edit:
Very unclear, see my third comment... ;)

**Comment by henrikssn** [comment]
We currently list all controllers, so that is why it is included

**Comment by davidwessman** [comment]
Yeah - and that needs fixing right? The user-control should have special handling.

**Comment by henrikssn** [comment]
So what is this special handling you are talking about? Somebody needs to be able to edit users too.

**Comment by davidwessman** [comment]
- Can every user edit their own user-info? (without having a post with user-permissions)
- Who should be allowed to edit other users?

**Comment by henrikssn** [comment]
1. Yes of course.
2. Spindelmän?

**Comment by davidwessman** [comment]
Okay, then I understand it a bit more - den we should just scope the:
```Permissions.all```in the controller:
https://github.com/fsek/web/blob/master/app/controllers/posts_controller.rb#L58

**Comment by davidwessman** [comment]
I think this is not an issue, I just needed to sit down and understand Cancancan.
