### ISSUE TITLE
Permission: Council

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#127]
Should be able to set permission to edit all, or just edit the one they belong to.

**Comment by henrikssn** [comment]
This is true for more models. I think this is quite easy to fix.

**Comment by davidwessman** [comment]
Wrote ref. on wiki:
https://github.com/fsek/web/wiki/Cancancan#define-ability-with-hash-of-conditions

**Comment by henrikssn** [comment]
Do we need to be able to do this for dynamic abilities?

**Comment by davidwessman** [comment]
What do you define as ```dynamic abilities```?

**Comment by henrikssn** [comment]
De som kommer från Permission modellen. Dvs. de som inte är definerade i ability.rb

**Comment by davidwessman** [comment]
Inte vad jag kan komma på.

**Comment by davidwessman** [comment]
When I think about it, we should define it for the dynamic abilities - since we want to choose for each ```Post``` if they are allowed to edit the ```Council``` that they ```belong_to```

**Comment by henrikssn** [comment]
Ok, kan fixa detta vid tillfälle.

**Comment by davidwessman** [comment]
There has been no need for this for soon 2 years, might be a future feature if the need arises.
