### ISSUE TITLE
Permission: Posts

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#128]
How do we allow people to edit posts (for example Valberedning) but not edit their permissions?

**Comment by henrikssn** [comment]
We currently can't (without a hack). Hmm, maybe we should had

    Post:
      belongs_to :role
    Role:
      has_many :permissions, through: :permission_posts

**Comment by davidwessman** [comment]
Because I think permissions should be set by admins. 
Or what do you think?

**Comment by jforberg** [comment]
Put a separate edit action in the controller, like edit_restricted and just filter out the permission params. This is why we like strong_parameters.
