### ISSUE TITLE
Remove old tables in Production database

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#129]
In ```schema.rb```
https://github.com/fsek/web/blob/master/db/schema.rb
there is a lot of old tables which is not in use anymore:
- ```email_accounts```
- ```emails```
- ```lists```
- ```phrasing_phrase_version```
- ```phrasing_phrases```
- ```roles``` (when Cancancan is implemented, unless it is needed -> see: #128)

Should we remove this or not?

**Comment by jforberg** [comment]
Yes, if they are not used they should be dropped.

**Comment by davidwessman** [comment]
Can you fix this? 
Not sure what we decide about ```role```.

**Comment by jforberg** [comment]
I can but I'm a bit busy now and will be for a week. It's not hard to do if you have time on your hands.

**Comment by henrikssn** [comment]
*It's not hard to do if you have time on your hands.* - @jforberg 

No but you really need to know what you are doing :)

**Comment by jforberg** [comment]
@henrikssn We do make regular backups don't we :)

But sure, we are not in a hurry at all, I can do it in a week or so.

**Comment by jforberg** [comment]
It seems someone has removed them now so I'm closing this.
