### ISSUE TITLE
Integration tests to avoid -> Election: cannot edit

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#133]
They are having interviews for the election today and really needs the information.

**Comment by davidwessman** [comment]
We need to implement better integration tests to catch this.

**Comment by henrikssn** [comment]
We do not have any integration tests for signed in users, so yeah :)

**Comment by davidwessman** [comment]
https://github.com/fsek/web/blob/master/spec/features/admin_visit_spec.rb
However it is not implemented with election + edit.
