### ISSUE TITLE
Cafebokning: Cafetävling

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#14]
Ett sätt att hålla koll på Cafetävlingen.
Varje pass som någon jobbar kan man välja att representera ett utskott samt vara med i den individuella tävlingen.
Just nu har vi:

CafeWork:
belongs_to :profile
has_and_belongs_to_many  :councils

Profile:
has_many :cafe_works

Council 
has_and_belongs_to_many :cafe_works

Individuella pass är inte så svårt, frågan är vad man gör lättast för att t.ex. hitta den som leder den individuella tävlingen.
Jag vet inte riktigt om man kan använda scopes eller något smart ActiveRecord för att köra det direkt i databasen. Annars skulle jag säga att loopa igenom läsperiodens arbetspass och på så sätt räkna.

Tips och idéer behövs!

**Comment by supernovan** [comment]
Antar vi lagrar det i någon trevlig variabel i en användare eller något
liknande, kan vi inte loopa igenom och bara spara den som har högst värde?

2015-02-22 23:47 GMT+01:00 David Wessman <notifications@github.com>:

> Ett sätt att hålla koll på Cafetävlingen.
> Varje pass som någon jobbar kan man välja att representera ett utskott
> samt vara med i den individuella tävlingen.
> Just nu har vi:
>
> CafeWork:
> belongs_to :profile
> has_and_belongs_to_many :councils
>
> Profile:
> has_many :cafe_works
>
> Council
> has_and_belongs_to_many :cafe_works
>
> Individuella pass är inte så svårt, frågan är vad man gör lättast för att
> t.ex. hitta den som leder den individuella tävlingen.
> Jag vet inte riktigt om man kan använda scopes eller något smart
> ActiveRecord för att köra det direkt i databasen. Annars skulle jag säga
> att loopa igenom läsperiodens arbetspass och på så sätt räkna.
>
> Tips och idéer behövs!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsek/web/issues/14>.
>



-- 
Med vänliga hälsningar
Mattias Josefsson

**Comment by SirDirac** [comment]
Typ (sql):

​

​Select count(id) as x, user_id from cafe_works group by user_id sort by x desc;

**Comment by jforberg** [comment]
Översatt till rails blir det lite krångligare eftersom vi måste stå på den tabellen vi vill mappa till. Säg,

```
ps = Profile.select('name, count(*) as score')
       .joins('right join cafe_works on profiles.id = cafe_works.profile_id')
       .where('lp = ? and year(work_day) = ?', hämta_nuvarande_läsperiod, Time.now.year)
       .group('profile_id')
       .order('score desc')
       .limit(5)

ps.each_with_index do |p, i| 
  puts "#{i}. #{p.name} med #{p[:score]} jobbade pass"
end
```

Här har man hårdkodat kolumnernas namn men jag ser inte hur det går att undvika i en förhållandevis invecklad fråga (med rails-mått mätt) som den här. Where-satsen går dock lätt att bryta ut.
