### ISSUE TITLE
Which Font do we use?

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#142]
The Board are thinking about changing the Font.
Which one do we use?
@fsek/admins

**Comment by henrikssn** [comment]
Helvetica Neue

https://github.com/fsek/web/blob/3c42d7b0525fa2b4c5ca514811e9baad536fb0d2/vendor/assets/stylesheets/bootstrap.css#L276

**Comment by davidwessman** [comment]
Okay. Thanks

**Comment by davidwessman** [comment]
They are having problem with license of Helvetica Neue for other units than Mac, so they are thinking about changing Font in the graphical profile.
But we still have to rework our css, so changing the font wouldn't be an issue right?

**Comment by davidwessman** [comment]
Not gonna happen anything now, closing.

**Comment by jforberg** [comment]
It was me who selected Helvetica as the official font when I wrote F-sektionens graphical profile back in 2012. Initially it was just going to say "Helvetica" but then someone thought that Helvetica neue was better so I went with that.

I doesn't really matter though and especially not on the web. Just use any Helvetica clone with a good license.

**Comment by davidwessman** [comment]
The ```neue```-license is the problem, but they will not fix it for this semester, will be for the next.
