### ISSUE TITLE
Testing: Feature tests with Capybara

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#143]
How do we design our feature tests?

A feature login test is implemented in #141.
- Do we cover every module?
- Do we create failing tests or just the correct usage?

We need some guidelines.

**Comment by henrikssn** [comment]
We should test correct usage and all modules should have at least one feature test

**Comment by jforberg** [comment]
Yes. A good rule is to have at least a "happy path" (correct usage) and "sad path" test (invalid usage) test for everything. This is actually really useful in Rails as it is so dynamic, compilation errors can occur at runtime etc. So in the simplest case we are just checking that a feature is actually there and does not crash.

**Comment by davidwessman** [comment]
I saw an article about using classes in the feature tests. For example if you change your login layout we have to change every test with a login. So we should create helper classes for common actions.

**Comment by davidwessman** [comment]
I implemented this:
https://github.com/fsek/web/blob/master/spec/page_objects/login_page.rb

Makes it quite smooth to login (not testing the login every time).
```
login.visit_page.login(user, '12345678')
```
Will log in the user with the given password.
This way it is easier to change this if we change the login procedure.

**Comment by henrikssn** [comment]
:+1:

**Comment by davidwessman** [comment]
This is not an issue, more how to do things.
Added the login code to https://github.com/fsek/web/wiki/How-to-write-an-integration-test
