### ISSUE TITLE
Fsek/web - closed or open source?

### ISSUE THREAD

**Issue by jforberg** [fsek/web#155]
I'd like to raise the question if we should close the source to the fsek/web app. 

*Implementation detail: Currently we don't have any closed repo tokens but you can get them for free if you convince Github that you are a student organisation. They are quite easy to convince.*

I'm just going to list some arguments and counter-arguments and let's discuss

**Arguments for open-source:**
* Easy for any member to report bugs as issues. 
 * Does not seem to be happening. Also this is not necessarily something we want. The contact webform is probably a nicer interface for n00bs who might be confused by our often technical discussions. 
* You can participate in coding even if you're not a spindelman, just check out the code and have at it
 * Yes, but maybe we want to encourage people to become spindelmän if they like coding
* Open source is cool
 * True, but currently our codebase is not in a state where someone could (probably) have any use for it. Also it has some ugly parts that we are not that proud of.
 * A better pattern may be to put any interesting code that we write into a new gem, as that is how "open-source" usually works in the Rails world.

**Arguments for closed-source:**
* More secure, not so easy to find vulnerabilities by reading the code
 * Perhaps, but "security by obscurity" is not real security, see [Kerckhoff principle](http://en.wikipedia.org/wiki/Kerckhoffs%27s_principle)
* We don't have to worry about what we check into git, can put sensitive information in the code
 * Mostly a convenience, can be solved in other ways.
* We can write really ugly code and nobody has to know.
 * But maybe we need a bit of motivation to de-uglify our current codebase.

There are probably more arguments that I'm not listing, let's hear them.

**Comment by davidwessman** [comment]
I do not think there are enough reasons to keep it open source, if we can get a closed repo that would be nice 😄

**Comment by supernovan** [comment]
If it's possible try to make it a closed repo. I prefer to sometimes be able to write ugly code sometimes due to the fact I actually have to in some situations. Futhermore as far as I know none of us really know how to make the website secure, so why not protect it in the meantime by concealing the code.

**Comment by henrikssn** [comment]
All the nice tools we use (travis, hound, codeclimate, haikiri) costs money when the repo is private.

**Comment by davidwessman** [comment]
Yeah, it would cost alot to get something similar :/

**Comment by jforberg** [comment]
We like our free tools.

Closing.
