### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#162]
With Nginx the ```client_max_body_size``` is too small, when uploading a Document over 1 MB it fails.

@jforberg @henrikssn Can you fix this?

Ref:
http://cnedelcu.blogspot.se/2013/09/nginx-error-413-request-entity-too-large.html

**Comment by henrikssn** [comment]
Changed to 100MB. Please verify before close.

**Comment by davidwessman** [comment]
Worked, GJ
