### ISSUE TITLE
Refactor Rent from an F on Code Climate

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#163]
https://codeclimate.com/github/fsek/web/Rent

**Comment by henrikssn** [comment]
The model is a mess, this can probably be done in an easier way.

**Comment by davidwessman** [comment]
I think there is rework in #52, gonna try to get this done. At Kårhack this weekend, will probably be some RoR done.

**Comment by henrikssn** [comment]
Lets get those PRs merged :+1:

**Comment by davidwessman** [comment]
Sitting next to Albin who started the Eventanmalan branch as well, so perhaps we can close 3 tonight or tomorrow ;)

**Comment by davidwessman** [comment]
Done! Wohooo! #247
