### ISSUE TITLE
Style: Align the elements of a hash literal if they span more than one line.

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#164]
We should either edit what Hound says about this one, or get a working vim-config to format our files.

The error is when breaking elements in a hash into multiple rows.
In a method where the second argument is a hash of attributes it becomes this:
```
patch :remove_worker, id: cwork_access.to_param,
      cafe_work: { access_code: cwork_access.access_code }
```
Is how my current vim config will format this with `==` on every row.

And this is how hound will accept it:
```
patch :remove_worker, id: cwork_access.to_param,
                      cafe_work: { access_code: cwork_access.access_code }
```

Will be the same if I call :
```
patch(:remove_worker, id: ID,
      cafe_work: params)
```

What do you think?

**Comment by davidwessman** [comment]
@jforberg  @henrikssn

**Comment by henrikssn** [comment]
The Hound is right about this one

**Comment by davidwessman** [comment]
Any VIM-solution? I tried to find something but no luck yet

**Comment by henrikssn** [comment]
Nope. I'll tend to align these cases manually. Vim remembers the alignment after the first line.

````
foo :bar, zero: 0
          first: 1 # Needs manual tabbing in vim
          second: 2 # Vim now remembers so this is auto

**Comment by jforberg** [comment]
I'm with @henrikssn. Maybe there is a vim-script to do this automatically (in which case, do link to it) but I've always done this by hand.

Note, if you are writing HAML templates then it's better to do it this way:

```
= some_very_long_railsy_method_name :arg => value, 
  :other_arg => other_value
```

It's hard to explain why but you just get fewer indentation errors if you do it like that.

**Comment by davidwessman** [comment]
Okay, so we should handle this manually. 
Then it might be worth to refactor like this:
```
params = { id: access.to_param, 
                  cafe_work: { access_code: access.access_code } }
patch :remove_worker, params
```
And then the `==` format can handle it.
