### ISSUE TITLE
Post: Edit post

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#165]
This line fails:
https://github.com/fsek/web/blob/master/app/views/posts/edit.html.erb#L7

Should be ```PermissionPost```, and we need an integration test for this.
Will fix in next PR I finish.

**Comment by davidwessman** [comment]
#166

**Comment by jforberg** [comment]
Maybe you know this but to be clear:

```
can? :modify, PermissionsPost
```

Means 'is there *some* situation in which user would be able to modify *any* permissionspost'. So as long as the user can modify a single instance, under some set of conditions, this will be true. A common error is to think it means 'can user modify *all* permissionspost'.

It's always better to test against a specific instance if you have one. This is the way cancan is meant to be used. It's OK to make a new object just to test against, e.g. in this situation I would do:

```
can? :modify, PermissionsPost.new(:post => @post)
```

Which then answers the question, 'can user modify a permissionspost given that the post is @post'

**Comment by davidwessman** [comment]
:+1:

**Comment by jforberg** [comment]
https://github.com/fsek/web/wiki/Cancan:-Testing-against-classes

**Comment by davidwessman** [comment]
Perfect 😄

**Comment by henrikssn** [comment]
Great @jforberg, I had no idea about that when I write the code. Thanks!
