### ISSUE TITLE
Post: Active/Inactive

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#167]
People like their Posts  and would like to be able to show old posts as well.
Since the Permissions comes with the post now - how would we do this the best?
We could set some kind of dates and active/inactive status to see wether they still should have the permissions.
What do you think?

Would be cool to see **Spindelman 14/15** (even though Spindelman is for life) even after you leave the post.

**Comment by henrikssn** [comment]
Add another model old_post to the profiles

**Comment by davidwessman** [comment]
Like:
```
class OldPost << ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_one :council, through: :post
end
```

And with what year they had the post and so on.
This object is created when they leave their post?

**Comment by henrikssn** [comment]
Skip the belongs_to :post, it is not really relevant here.

````
class OldPost << ActiveRecord::Base
  belongs_to :user
  #string name
  #date year
end
````

Yes, create this when people leave their post.

**Comment by davidwessman** [comment]
Why not join it with Posts?
Then you can look at a post and see old users who've had it and so on.

**Comment by jforberg** [comment]
I don't think a new model is necessary.

Instead I would make two scopes on Post: active and past. Past posts are just like active posts except for a single column.

Then in the user view you do:

```
User.posts.active.each do { print it out }
User.posts.past.each do { print it out }
```

**Comment by henrikssn** [comment]
And then you link User.posts to User.posts.active :)

My worry was that we may remove/rename a post which will break the old post for people. Say we rename Spindelman to Webmaster (why would anyone do that?). Then I want to have Spindelman '15 in my profile and not Webmaster '15.

**Comment by jforberg** [comment]
@henrikssn That is actually a good point. I can think of two ways to handle that:

1. Specifically track for each Post-User what the name of that post was at the time.
2. Require that post renames are handled as a new post.

I think we can safely postpone this until it becomes a problem :)
