### ISSUE TITLE
CafeModule: Nyckelpiga

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#169]
http://fsektionen.se/hilbertcafe/nyckelpiga
Should render the ones working for current or selected day to the ones who are in charge of Hilbert Café.

The date-select is rendered and works, but not rendering any workers.

**Comment by jforberg** [comment]
@davidwessman Your bug reports are a bit hard to understand sometimes. More info would be appreciated.

**Comment by davidwessman** [comment]
@jforberg 
Just wrote this in a rush, sorry. Updating comment.

**Comment by davidwessman** [comment]
Fixed in #191
