### ISSUE TITLE
Shortlinks

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#170]
It works like normal, but when trying to create:

algresa -> https://docs.google.com/forms/d/1OmoiEvqY4unNCsdJNMbGIMI5cYdBf
xlyymKpUVnskOU/viewform

Not sure what is the problem here.

It does not create and then fails to render index view.
@jforberg

**Comment by henrikssn** [comment]
Det funkar om du inte har ett mellanslag i url:en

algresa -> https://docs.google.com/forms/d/1OmoiEvqY4unNCsdJNMbGIMI5cYdBfxlyymKpUVnskOU/viewform

**Comment by henrikssn** [comment]
Dock kanske servern bör hantera detta bättre än att ge Error 500

**Comment by davidwessman** [comment]
Haha, spännande! ;) 
Yepp, det borde den.

**Comment by henrikssn** [comment]
Jag föreslår att ge en "Invalid url" error-flash.

**Comment by davidwessman** [comment]
Det finns ju redan en del validations och ja, man borde inte ha mellanslag med i en url, men det vore ju fint om det kunde testa? 
För visst kör den en check innan?

**Comment by jforberg** [comment]
Valideringarna bör vara korrekta. Den använder en riktig URL-parsare, samma som Rails internt.

Just nu presenteras inte någon feedback på valideringar. Detta har jag förvarnat styrelsen om men på sikt vill vi förstås visa lite bättre feedback.

**Comment by jforberg** [comment]
500 är fel. 500 betyder "vårt fel" men detta är uppenbart "ditt fel". 422 hade varit bättre.

**Comment by davidwessman** [comment]
Okej, drar rails 500 om validation misslyckas?

**Comment by jforberg** [comment]
500 är kod för ett exception som inte hanteras. Jag trodde att vi fångade alla validation errors i ApplicationController men uppenbarligen inte.

**Comment by jforberg** [comment]
@davidwessman Samma problem här, någon hade tagit bort översättningen...

**Comment by davidwessman** [comment]
Jag ändrade ganska mycket i Locales, troligtvis mitt fel - sorry, trodde att allt kom med.

**Comment by jforberg** [comment]
Samt bytt namn på nycklarna i flashen :) kan vara värt att greppa lite i koden nästa gång du gör nån liknande rockad.

Om du t.ex. tycker att flash[:error] borde heta flash[:alert] istället, så går det fort att göra en grep -R 'flash[:error]' för att se så att ingen räknar med det gamla namnet.
