### ISSUE TITLE
Profile -> Users: extra fields

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#178]
Since we have allowed non registered users to rent the car and work in Hilbert Cafe we stored all the information in the several places.
For example if we have a user who rents the car, they still fill out a form and store their name, phone, email in the Rent-table.
Is this still motivated? 

Case 1:
Someone rent the car and, for whatever reason, delete their user afterward.
Then there would be no way to know who actually had the car(atleast DB-wise). 

Because now when a user visits for example `new_rent_path` we have a method setting their attributes on the `rent` as well.

Case 2:
Someone rent the car, then they change their phone number and update their user-info.
Then it would be great if old rents would get this change as well.

What do you think? How should we handle this the best way?

**Comment by jforberg** [comment]
Just create a new user with the correct name. Define "registered" user as a user which has an email (or any other column defined).

Don't allow users to delete themselves. Why would you want that? Just set some flag on the user to mark it as deleted. If you're worried about PUL, maybe you want to nuke any personal information as well. But in general you do not want to delete any records.

Also look at Devise::Models::Authenticatable.active_for_authentication?

**Comment by davidwessman** [comment]
So if we go with the idea of not deleting users.

Do you think we can remove the datafiels from Rent-, and CafeWork-table and just use an association?
It does make things easier.

**Comment by henrikssn** [comment]
+1 on @jforberg, there should be one source for information like email, name and phone: This is the User model.

Another thing: We should enforce that there are only one account per student. Currently the whole earth could sign up using my personal number (easily obtainable online) and that is not a very secure solution. 

I propose either
1. store the personal number
2. enforce that people use their @student.lu.se email.

**Comment by davidwessman** [comment]
Okay.
Then we can remove lots of fields 😄

We could save it with asymmetric hashing? And just compare with that? 
Because I do not like storing everyones personal number ;)

**Comment by jforberg** [comment]
Is there a reason why we need their personal numbers? Like, a real reason? If it's only for car renting then that should be a separate check.

I usually don't register at random internet pages with my personal number. Although, like @henrikssn my personal number is public information as I run a company. No getting away...

In the past, we used a system where people who had (real) @student mails were approved immediately and people who didn't had to be greenlighted manually. Could this work?

**Comment by davidwessman** [comment]
@lham Wrote a neat check towards http://medcheck.tlth.se/
So like now we havn't saved any personal numbers, just used it to see if they are members.

**Comment by davidwessman** [comment]
And if we would only look at their email, then we have no way of distinguishing if they are from F-guild or even LTH.

**Comment by jforberg** [comment]
@davidwessman I don't think it's a problem if people from other programmes register at the site. We don't have any kind of secret information available to general users (if we do then we shouldn't). In the past we let other sections register.

I think we should open registration to all students and then have an optional check for membership for those services that require it.

If you look at current systems that are working well then they either have no checks at all (TLTH car booking, very high use) or only check student email (D-sek website).

The more checks you have, the more support you need to provide...

**Comment by davidwessman** [comment]
Hmm, I do feel like I want to differ the guild members with others.
Perhaps we should check with the board what they think as well.
What do the rest of the team think? @fsek/admins

**Comment by jforberg** [comment]
@davidwessman I'm not saying we shouldn't make a difference. I'm saying the default should be that you're just any student. Then "F-student" could be a higher access level which you can get by validating your PNR.

A good example of stuff that might require "F-student" status is renting the car, maybe nominating someone.

TLTH has comprehensive information on all members (and past members) which we can access if we need to.

**Comment by jforberg** [comment]
@davidwessman Also, if we need to we can probably get direct access to the API which MEDCHECK uses.

It's a very limited API but you can do two things with it:

1. check_member(pnr) => { boolean, section }

2. lookup(pnr) => { json data about the student }

**Comment by davidwessman** [comment]
@jforberg 
I totally agree with you there! 
That is kind of the way I've started in #109. 
As it is right now, anyone can rent the car ( I think ), and we want people to register in order to rent the car - then we need to allow any email.

Where can you find information on the API? Because that would be great 😄

**Comment by jforberg** [comment]
There was some information online but now I can't find it. But it's basically like what I wrote, it can't do much more than that.

**Comment by jforberg** [comment]
@davidwessman Or what you could do is just read the source of MEDCHECK...

**Comment by davidwessman** [comment]
When you say 
> ...read the source of MEDCHECK...
What do you mean by that? Where can I read it?

Some guidance would be gr8, I have no clue what to do :)

**Comment by jforberg** [comment]
Sorry.

Well, medcheck is closed source, original "fulhack" by some D-student. And you would need to get an API key from TLTH. The guy to talk to is Daniel Lundell, daniellundell91@gmail.com.

The API itself, it's been some time since I used it but it's a simple JSON API. No prob.

But you should probably have some use case in mind before you go asking for keys.

**Comment by davidwessman** [comment]
Extra fields remaining in:
-  [ ] `CafeWork`
-  [ ] `Candidate`
-  [ ] `Rent`

**Comment by davidwessman** [comment]
Closed in #457
