### ISSUE TITLE
Motionsmaskin trasig

### ISSUE THREAD

**Issue by jforberg** [fsek/web#179]
Min fina motionsmaskin är trasig :(

**Comment by henrikssn** [comment]
It's not, all tests still pass. Oh wait... ;)

**Comment by jforberg** [comment]
@henrikssn Show me a way to test PDF output and I'll write them :)

Ok, a feature test for "not HTTP 500" would be a good idea.

BTW I have actually not commited to master since I wrote that code, so as I see it this bug is **your** fault... :neckbeard:

**Comment by davidwessman** [comment]
Such wow, much blame. :8ball:

**Comment by henrikssn** [comment]
"not HTTP 500" tend to catch many problems.

You could probably feed the feature test with a PDF and do a binary diff on the one from the machine, but I would regard that as overdoing it.

Tests are always the responsibility of the guy writing the code :)

**Comment by jforberg** [comment]
Fixed this. Someone had deleted the translations for my code...
