### ISSUE TITLE
Improve code style

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#18]
CodeClimate has an extensive list of things need fixing.

https://codeclimate.com/github/fsek/web/issues/categories/style

**Comment by jforberg** [comment]
This is true but it is an ongoing struggle, not a task that can be "performed" really.

When it comes to style, as usual I stand by the views of [mr. Spolsky](http://www.joelonsoftware.com/articles/Wrong.html): the correct approach to bad style is to refactor it as you go along.
