### ISSUE TITLE
Data transfer: Candidates, News

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#188]
When merging the data wasn't transfered:
```
irb(main):004:0> News.last
=> #<News id: 29, title: "Projektgruppen till FARAD 2016", content: "Det är nu möjligt att söka till projektgruppen til...", front_page: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, created_at: "2015-05-07 20:51:11", updated_at: "2015-05-07 20:51:11", profile_id: 295, user_id: nil>
```

And same with all `candidate` and all other `news`.
@henrikssn Taking care of it.

**Comment by jforberg** [comment]
Is this resolved @davidwessman ?

**Comment by davidwessman** [comment]
Nope. A lot of ids missing.

We also have duplicates of Post_users, since we didn't have unique validations when we did the migration.

**Comment by jforberg** [comment]
This can easily be done interactively I think. What exactly needs to be done?

**Comment by davidwessman** [comment]
If you look at https://fsektionen.se in the News-column, the News Item you posted has got your link, the rest doesn't, this is because their user_id is still nil, but there is a profile_id left.

This is also the case for all candidates.

**Comment by davidwessman** [comment]
Hmm, we have removed the `profile_id` of both candidates and news 
(when we removed the rest of profiles).

I was thinking that old candidates can be linked by looking at stil_id for example. But there is an after_save trying to send emails ;) 

So I guess this can be closed.
