### ISSUE TITLE
Rspec: running in wrong environment

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#189]
I cannot find the culprit here, but for some reason my `RAILS_ENV` is already set to `development`and therefore every rspec-command resets my DB.

It works to run `RAILS_ENV=test rspec` but it would be nice to get this to work just from the `rails_helper` or `spec_helper`.
Any clues?

**Comment by henrikssn** [comment]
`rspec` should by default run in `test` environment. No idea why it isn't.

**Comment by davidwessman** [comment]
Do rspec run in `test environment` for you?

**Comment by jforberg** [comment]
Yes.

What kind of setup do you have? RVM? Rbenv? Ruby from source?

Do you have any strange ENV variables?

Did you install any rubygems from your distros packages?

**Comment by jforberg** [comment]
Closing this as it's a problem with @davidwessman setup, not the app.

Wessman can message me or anyone else if he still has problems.
