### ISSUE TITLE
Prepare for Rails 5 (Fall 2015)

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#198]
http://www.sitepoint.com/whats-new-rails-5/?

**Comment by jforberg** [comment]
Sure, let's upgrade. Although we can probably wait until the stable release is out.

I've looked through the changelogs, doesn't seem to be anything major added actually.

Except now we can finally do OR in our active record queries... Not sure why that took 10 years to happen.

**Comment by davidwessman** [comment]
No rush with this, just so we can prepare a bit 😄, definitely waiting for a stable release 😄 

Seems like people are moving towards using Rails as API and using JS as front as well.

**Comment by jforberg** [comment]
JS front ends are nice but they are much harder to debug in my experience. For what we do (simple views with little or no interactivity) old-skool templating should be sufficient and is a much lighter maintenance load.

**Comment by davidwessman** [comment]
Will do this when Rails 5 is here.
Beta-1 launched a few days ago, should have been launched in August or something ;)
