### ISSUE TITLE
Eventmodul: skapa återkommande event

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#2]
Lägg till funktion för att skapa ett event som kan återkomma veckovis eller att man kan lägga till flera datum eller liknande.

**Comment by davidwessman** [comment]
@fsek/admins 
Vad säger ni om att lägga till en model som bara beskriver start och sluttid, så kan dessa användas för att lägga till flera datum för samma event?

Att varje Event ```has_many``` EventTimes?

**Comment by jforberg** [comment]
Om man vill göra detta så är det snygga att ha en egen tabell för tiderna, som du beskriver.

Jag undrar nog mest om detta är nödvändig funktionalitet. Det komplicerar ju gränssnittet en del. Jättarna facebook mfl. klarar sig utan.

**Comment by davidwessman** [comment]
Efterfrågat av Sanningsministeriet.

**Comment by jforberg** [comment]
Efterfrågat != nödvändigt.

Ytterst är det du som äger den här funktionaliteten (typ) så du får bedöma. I ditt ställe hade jag prioriterat att hålla koden och framförallt gränssnittet enkelt.

**Comment by davidwessman** [comment]
Perhaps we can add an action on an Event to create a new one where it suggest next week/month.

**Comment by jforberg** [comment]
Yes, that's a very good solution actually. It just needs a tiny bit of javascript, no views, controllers, models, tests yada yada.

Good call!

**Comment by davidwessman** [comment]
Hmm, not 100% sure how you would do it with JS?
I'm thinking of an action where the form is populated with a prepared event.

This could be done with a new route and a controller action which renders the `new` template 
or with a `GET` request with attributes as parameters.

**Comment by davidwessman** [comment]
Has not been requested for long.
