### ISSUE TITLE
Refactor FAT controllers

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#20]
Lots of the controllers do have very much model business logic.
Should be refactored.

**Comment by Zofz** [comment]
The controller for the Rent-module refactored

**Comment by jforberg** [comment]
If we intend to refactor all controllers, we should also take this moment to

* Port our controllers from the_role to cancancan, if we want to do that. Cancancan is the industry standard and also IMO a much better solution.
* Stop hardcoding activerecord error handling in each action and instead use exceptions and unified error handling. I.e. a single ```rescue_from ActiveRecord::RecordInvalid``` which handles all errors for all records. Also in rails you can change the form dynamically to react to errors, marking them read etc. I can show you how to do this.
* Move from ```respond_to do |format|``` to ```respond_with @resource``` wherever we do not need special logic for JSON/HTML responses.

All this wil become much harder to do later.

What do you think? I could refactor one controller as \*I\* think it should be and then you can decide.

**Comment by Zofz** [comment]
@jforberg, nice ideas.

How do you like too setup the cancancan? 
I read some about Abilities, but how do you add it dynamically?
(ref: https://github.com/CanCanCommunity/cancancan/wiki/defining-abilities)

How do you do the error-handling? 
I haven't read much about any best practices there, do you have any examples?

is the '''respond_to''' and '''respond_with''' changes in rails?
An example of a whole controller would be great, perhaps so that we can compare with how it looked before.

**Comment by jforberg** [comment]
It's not so much about best practices as Don't Repeat Yourself. Whenever you're repeating yourself, especially in an expressive language like ruby, you should start to feel your fingers itch...

Whenever I have time I'll show you how it works in one controller.

**Comment by jforberg** [comment]
Time was found.

Look at this:
https://github.com/fsek/web/blob/68905d6aad99d51631382122f9e9af098bd1d277/app/controllers/news_controller.rb
also
https://github.com/fsek/web/blob/68905d6aad99d51631382122f9e9af098bd1d277/app/models/ability.rb

**Comment by henrikssn** [comment]
@Zofz @jforberg On the topic of repeating yourself. Code climate have tons of examples where this happens in our code.

https://codeclimate.com/github/fsek/web/issues/categories/duplication

**Comment by Zofz** [comment]
@jforberg 
How is ```load_and_authorize_resource``` defined? That is a CanCan-action?

https://github.com/fsek/web/blob/dry/app/controllers/news_controller.rb

**Comment by jforberg** [comment]
Most of this is in the docs but it goes like this (note that the new gem is called cancancan, not cancan which is the old, unmaintained one)

1. load_and_authorize_resource does the right thing most of the time. In a show action in a PeopleController, it means

```
@person = Person.find params[:id]
authorize! :read, @person
```

in the update action it means

```
@person = Person.find(params[:id])
@person.assign_attributes person_params
```

Most of the time it does the right thing, sometimes you have to :skip => it and do a manual authorize! check.

The reason we have to load the resource before the check is that access may depend on any attribute of the resource. So we have no way of knowing if access is allowed before we have seen the object.

Yeah, you're supposed to use strong_parameters just like usual, cancan doesn't do anything special with that. I was drunk when I wrote the code above so I forgot.

**Comment by jforberg** [comment]
This is mostly done now. Open new issues for any current concentrations of fat in the code.
