### ISSUE TITLE
Rails 4.2.2

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#200]
I updated another project with no issues, but not all the dependencies are the same.
@henrikssn Can you do this?

**Comment by jforberg** [comment]
As this is a bugfix release, upgrading should be a no-brainer. I will submit a patch.

**Comment by jforberg** [comment]
Hmm, we are dependin on a **lot** of third party code.

```
johan@apollo ~/code/fsek $ cat Gemfile.lock | grep '^    \w' | wc
    139     278    3295
```

Do we really need 139 third party libraries? Could we live without some of them? This is probably the reason tests are so slow.

**Comment by davidwessman** [comment]
It is definitely time to clear some shit out I'd say 😄

**Comment by davidwessman** [comment]
#227
