### ISSUE TITLE
Gallery: Carrierwave

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#201]
It would be great if someone could start looking at the Gallery.

I think we should change to Carrierwave instead of Paperclip (it seems more dynamic),
what do you think?

Using hashed filenames and keeping the images in public-directory is probably the best solution for large amounts of files.

It would be cool to have video-support as well.

**Comment by henrikssn** [comment]
Something I would want to try is NoSQL and keeping everything in the database (yes, you can even put large photos in a NoSQL database). It is sharded if you have multiple database servers, that is, a picture is splitted over multiple servers and then reads happen in parallell.

I have tried MongoDB with the Mongoid wrapper (No database schema needed, yay!) and it is great. It works in tandem with MySQL so we can start by only putting the Album models in Mongoid.

This is totally unnecessary for our usage, but it is a very hot topic to know NoSQL so it is better time spent learning for ourselves.

**Comment by jforberg** [comment]
@davidwessman I also prefer Carrierwave, it's nicer framework although it doesn't hold your hand as much as paperclip does (a plus in my book).

@henrikssn NoSQL is cool but as you say completely unnecessary for us. If we do it then it's just for the cool factor, maybe a good enough reason :)

They manage to run all of Twitter mostly just on Rails / Mysql or did at least a few years back. Probably enough for us too :)

**Comment by jforberg** [comment]
For the record, I'm still a bit skeptical of our plan to write our own gallery module.

**Comment by davidwessman** [comment]
#265
