### ISSUE TITLE
CI: Change to Circle CI?

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#202]
I have been trying out CircleCI on another project - and with a similar size I'm finishing build, tests och deploy in 2.5 minuters. They are caching the bundle which really helps.

It works great with deploying to Heroku, not sure how it works with Samson and the setup we have right now.

What do you think? @fsek/admins 
https://circleci.com

**Comment by henrikssn** [comment]
How much longer is our build queue? We do run our tests on Samson too, so we can skip Travis if we feel it takes too long time.

Samson needs 2-3 mins to deploy. It is a bit longer than Heroku but I don't really feel it is worth optimizing.

**Comment by jforberg** [comment]
I'd prefer it if we don't change our build tools so often, we've just almost got our current setup running and comfortable.

Is the build/ci/deploy etc. system really a bottleneck for you?

**Comment by davidwessman** [comment]
When I think about it, I might have more to do with the local setup, because I had some tests doing okay locally but not on travis, but I think it's getting better.

No problem with keeping it as we have it right now.
