### ISSUE TITLE
Please don't make a PR until your code passes the hound

### ISSUE THREAD

**Issue by jforberg** [fsek/web#206]
@fsek/admins Hi guys. Me again. I've got another rant coming up.

Right now a typical pull request  on this project looks like this

![hound](https://cloud.githubusercontent.com/assets/1269005/8530804/854ce0d8-2423-11e5-88e5-bbba02273196.png)

It's ok if you don't know all our style rules by heart but please, don't post pull requests until your code passes (or at least nearly passes) the hound.

If you name your branch like ```jforberg/my-awesome-feature``` then everyone will understand that you own the branch and you can ```push --force``` to it. [Nobody cares. It's your branch](https://www.youtube.com/watch?v=4XpnKHJAok8&t=19m23s).

Also, in general it's a good idea to clean up your commits pre-merge so that they correspond to logical changes you have made. Git has wonderful tools for squashing together commits or even committing changes in the same file as separate commits. Namely, they are:

```
git commit --amend
git rebase -i
git add -p
```

Read up on these and *a lot* of things may fall in place. Now go out and make nice, clean git logs! :)

**Comment by davidwessman** [comment]
Looks very nice 😄 
How do you run your Hound checks? Local Rubocop? 
Can you explain what you do with your own branch? 
You create the branch, implement the feature, then where do you merge with a branch from the project? Or directly to master? 

:+1:  ```rebase -i``` looks cool

**Comment by jforberg** [comment]
I don't use any style checker, I try to read the diffs instead and usually I can catch most mistakes there.

Generally, I don't merge except into master. So long as you're working on a feature by yourself, you can always rebase instead of merging.

When your're developing features together with someone else, it doesn't happen too often but that's when you'd use a topic branch for that. But i'd still have a personal branch for my work and rebase the topic branch into that.

If you have the concept of a 'merge window' which is when you're allowed to put in new things, then you also need a 'develop' or 'pre-master' branch. But we don't do merge windows yet.

**Comment by jforberg** [comment]
At this point I won't enforcing a stricter git style but please at least consider my points.

Also, please read all diffs before pushing them because that makes a big difference for quality.

**Comment by davidwessman** [comment]
I'm trying to be better here, I love the `add -p` and trying to get better commit messages.
Also learnt how to rebase this weekend 😄

**Comment by jforberg** [comment]
It's good and leaning git is not time wasted. But I think that for a hobby project such as this ease of access is more important. We are getting more professional but we shouldn't take it too far IMO. I will gladly tolerate messy patches and some PHP-style code if it means more people can contribute.

**Comment by davidwessman** [comment]
(y) I agree with you there! 😄
