### ISSUE TITLE
Using the /lib folder or not.

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#207]
Hey, while trying to refactor some code I ran into this:

What should we put in the ```lib``` folder:
```lib/services/rent_service.rb``` or ```app/services/rent_service.rb```.

For code as specific as Rent I think the second alternative is more clear, what do you think?
@fsek/admins

**Comment by jforberg** [comment]
The classic rule is, do you need to pull in Rails classes like Active*, Action* etc.? If you do then by tradition they go in /app.

But IMO it doesn't really matter, put them where it makes the most sense.
