### ISSUE TITLE
Byta namn: Kalender => Matris

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#208]
Inför Nollningen ska vi ha en Nollematris, det ger lite helhet att döpa om vår kalender till Matris.

**Comment by jforberg** [comment]
Brukar inte nollningen ha en egen sida? Har de valt att samköra det med vanliga sidan i år?

Jag har inget emot att döpa om saker temporärt så länge vi inte komplicerar appen för mycket med nollningsspecifika regler. Om de vill ha mycket egen funktionalitet så kan det vara enklast att implementera den separat.

Dags att ha ett litet möte med föset?

**Comment by davidwessman** [comment]
Haft lite möte med föset redan.
Jag sitter och jobbar på en matris och sen lite sidor - men inte jättemycket.
Svårt utan att servern är uppe.

**Comment by jforberg** [comment]
Antar att detta är lite sent nu. Wontfix.
