### ISSUE TITLE
Course score

### ISSUE THREAD

**Issue by jforberg** [fsek/web#209]
So I have this new idea: There used to be a thing on the website called SRFwiki or Kurswiki or some such where you could write about the different courses on LTH, what's good about them, what's bad and general advice for people who are deciding on which course to take.

This was a great tool for master students etc. and could potentially be a way for students to encourage the bad courses to get better.

I think it's time to start this up again but now as a part of the general website. Also the format will be simpler (not wiki) and more focused on voting/ranking courses.

The idea is, you enter your program (specialisation) and year and the app shows you the best ranked courses available to you. Also there will be a facility for commenting/reviewing courses.

It's basically reddit for courses.

I've started doing the groundwork over at https://github.com/fsek/web/tree/jforberg/coursescore

Any feedback on this idea? If someone would be interested in helping me with the UI, that would be cool as well.

**Comment by jforberg** [comment]
RFC from @fsek/admins

**Comment by davidwessman** [comment]
Sounds like a great idea 😄 
Might need some administration after tough exams... ;)

**Comment by davidwessman** [comment]
https://github.com/fsek/web/blob/jforberg/coursescore/app/controllers/courses_controller.rb#L2
If you use ```load_permissions_and_authorize_resource``` and the model is called the same as the controller you can remove some code.
It will all the variables for the CRUD-actions 😄 
What kind of an UI where you thinking about? What information will we gather on each course? 😄

**Comment by jforberg** [comment]
I actually prefer writing out the actions, that way everyone understands what is happening. Explicit is better than implicit.

The UI will essentially be reddit but a little slimmed down. We won't gather more info than we need to, ideally just what is needed for the fulltext search (year, programs, credits, coursecode name) and the rest will be found through the course page link.
