### ISSUE TITLE
Tests are very slow

### ISSUE THREAD

**Issue by jforberg** [fsek/web#214]
Our test system is very slow. On my system (sixcore CPU, fully SSD) the test suite takes almost 5 seconds *just to load*. This is not really acceptable if you are trying to do TTD.

Not sure what to do about this. Rspec is famous for being slow, but maybe switching to another framework is too much work.

**Comment by davidwessman** [comment]
What are the alternatives?

**Comment by jforberg** [comment]
On second thought, maybe rspec isn't the problem.

I think the problem is that rspec needs to load the entire app before it can do anything. This can be avoided but it's a bit harder. I will think more about this.

**Comment by davidwessman** [comment]
https://netguru.co/blog/9-ways-to-speed-up-your-rspec-tests
This gave me a lot of insights where we can improve!
Especially limiting gem load and perhaps using Guard 😄

**Comment by jforberg** [comment]
This is actually hard because the framework encourages you to do it the wrong way. They champion the use of TDD etc. but the tooling they provide does nothing to help you.

Guard is not really a solution but it can help. I have used it in the past with varying success. Maybe it has improved, I will try it again.

This is a big failure of Rails, Rspec and related tools. What is the point of faster computers if the tools we use become slower at a faster rate than computers become faster.

**Comment by davidwessman** [comment]
I've started to TDD more and more. 
Running the whole suit takes a while, but running the a single current spec is usually 3-5 seconds for unit tests and a bit more for features.

Not sure if we have any place to improve on this atm, are we ready to close?

**Comment by jforberg** [comment]
I still think it's much too slow but since you're the one writing 90% of the code right now it's really mostly your opinion that matters.

Let's close.
