### ISSUE TITLE
Kill profile

### ISSUE THREAD

**Issue by jforberg** [fsek/web#220]
Is profile actually used anymore? It seems to duplicate the entire User model and not do very much more. Can we please kill it?

Also, when did current_user stop returning profiles and start returning users? That broke my code, the tests must have failed as well?

**Comment by davidwessman** [comment]
We did the merge in April or May. I think we just wanted to be able to use the data incase the whole transfer didn't work.
#174 have been waiting since.

**Comment by jforberg** [comment]
The database I'm not so concerned of. We can keep the data if you like.

What I do have a problem with is the dead code which remains in the tree and infects my code with bugs like c1de3b25c6a48c6d84e4f838f965333248b77901.

I will post a patch for this whenever I have time.

**Comment by davidwessman** [comment]
Closed by #223
