### ISSUE TITLE
"Pending" tests

### ISSUE THREAD

**Issue by jforberg** [fsek/web#226]
What is the reasoning behind these "pending" tests? Are they pending because they test code that is currently broken or because they test functionality which does not exist?

They are annoying because rspec reports them as failing, cluttering up the terminal and hiding any legitimate failures,

I will comment them out now, unless someone can explain what their purpose is?

**Comment by davidwessman** [comment]
The ones about EventRegistration was because I started to implement and ran out of time before the Nollning. They can be commented out or placed in another folder until we can finish registration for events.
The other two are tests which I did not manage to fix and couldn't find the source of
