### ISSUE TITLE
Deployment: restart server

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#229]
Not sure how to tell nginx/passenger to reload after a successful deploy.
Any clues? Seems like you should not do `system`-calls with it atleast.

There are some who just use a textile and `touch` it to let the server know it should reboot.

Could you look into this @jforberg?
http://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/

**Comment by jforberg** [comment]
Well, what **I** would prefer is a manual system where you ssh to the machine and do the deploy by hand, fixing any errors that occur. I'm not impressed by these automagical, push-and-forget deploy systems. I do think the daily build part is very beneficial though.

What I'm trying to say is, I'm not the right person to look into this.

P.S. Our webserver solution is currently configured just like your article recommends, except we don't necessarily log to stdout.

The way to reload the webserver is to say ```systemctl restart nginx```. This is exactly equivalent to ```kill -SIGHUP $(cat /opt/nginx/run/nginx.pid)```. See /etc/systemd/system/nginx.service for details.

**Comment by davidwessman** [comment]
Hm, I haven't been able to try it properly.

But I implemented Circle Ci with https://github.com/capistrano/passenger/
And deploys to stage seems to be working 😄

**Comment by davidwessman** [comment]
Working really good (y)
