### ISSUE TITLE
Dokument

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#23]
Refactor and sharpen up the view

Navigation

**Comment by lham** [comment]
Jag jobbar på dokumentsystemet!

**Comment by Zofz** [comment]
Great 😄 
Just comment here or make a Pull Request if you need any feedback or so.
Are you working on a branch

**Comment by lham** [comment]
Yep.

Now everything is done except breadcrumbs and some last UI touches.

**Comment by Zofz** [comment]
Good job, make a pull request 😄

**Comment by Zofz** [comment]
#53
