### ISSUE TITLE
External links library

### ISSUE THREAD

**Issue by hnykda** [fsek/web#239]
Hey. We today decided with David that my first attempt to help you will be adding simple link library. Here is concept I have in mind and will try to implemented.
# Purpose

In different sections it might be useful to display links to external sites of partner or useful sites, such as websites of Lund University, LTH union, Nations, sponsors, list of links for firstyears... For this it may be useful have these links organized and possibly categorized, so user or administrators can easily add them.
# Specification
### ExLink
- [x] `label` - this will be physically displayed on website
- [x] `url` - url of the link (`<a href="$url">$label</a>`)
- [x] `tags` - for categorizing we will use tags, which IMHO suits better then categories and support better query. ~~Tags will be model on it's own and `ExLink` will have `has_many :tags`, while tag will have `belongs_to :ExLink`.~~ ~~Some external implementation will be used, e.g. [act-as-taggable](https://www.reddit.com/r/rails/comments/2chtgw/tagging_in_rails_4/).~~ Tags will be implemented as a string separated by comma.
- [ ] `test_availability` - True/False entry for enabling/disabling tests for checking the response.
- [x] `note` - information about the link (how long it might be alive or actual, for what reason...)
- [x] `active` - True/False entry for marking active/inactive status
- [ ] `expiration` - date when the link will be marked as inactive

`ExLink` for _external link_ is better name than just `Link` because of ambiguity.
## Usage

Link library will have simple interface mainly for:
- [x] creating, deleting, editing tags
- [x] querying links by selecting one or multiple tags

We could possibly add:
- [x] RESTfull API in manner like `example.com/links/resp?tags=tag_name1,tag_name2`.
- [x] Images to each link
## Tests

Besides trivial test cases we could implement test for testing if the current link is alive (check response and fail when `resp == 404` or more strict `resp != 200`).

---

Does it make sense and is it what you had in mind David? If yes, I'll start to take a look at that. Please keep in mind that I've never worked in RoR and all web projects so far were mainly for fun, family or friends written in Python. Nevertheless, I will try and if I see that it's horrible, I'll stop :) .

---

I am updating this post based on the suggestion you have below.

**Comment by davidwessman** [comment]
Welcome to our humble gang!
This is the most detailed feature description yet - looks really good.

When you wrote sponsors and similar I felt the need for an image as well.
To be able to put up links with images, perhaps as a banner or something.

This can be a following feature 😄 

For linking in rails there is a helper method (here comes the magic!) which you use in the `*.html.erb`views:

`<%= link_to(@link.label, @link.url, target: :blank) %>`
Where the `<%= %>` is to separate html and ruby, `@link` is an instance variable.

Just get back to us with any questions you have 😄
And push your code to a branch named after yourself so we can see your progress :)

**Comment by kotrfa** [comment]
Sure I will. Thank you for the info.

**Comment by jforberg** [comment]
Looks like a good idea. The interface will be the big part if you want to do it well, I think.

Acts_as_taggable is ok but is a slightly complicated solution to a simple problem. Consider if you want to pull in an external dependency for this small task. Unless you think you need the class-polymorphism of a.a.t., if you don't then I'd recommend just using a simple string column and writing out the queries.

**Comment by kotrfa** [comment]
Thanks. So this basically [this](http://www.sitepoint.com/tagging-scratch-rails/)?

**Comment by jforberg** [comment]
That would work. Or you could of course use a library but it's good to know the alternatives.

**Comment by kotrfa** [comment]
I think I will go with the simple model first without using the library, since these is my first hands-on ruby on rails.

**Comment by kotrfa** [comment]
Please see the [PR: External links library](https://github.com/fsek/web/pull/245). I edited the first post :) .

**Comment by davidwessman** [comment]
I love the checkboxes!

**Comment by davidwessman** [comment]
I do not think we have any need for this feature anymore, even though you did a very nice job @hnykda :) The most structured issue ever!
