### ISSUE TITLE
Tinyurl typ

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#24]
Implement a way to create redirect links like ```http://fsektionen.se/link/undersokning``` instead of the current ```www.tinyurl.com/fundersokning```.

Wishes from the board.
Any problems with implementing this?
Should you include some nice confirmation or just redirect directly?

**Comment by jforberg** [comment]
1. This is great. TLTH had this, don't know how I would have been able to work without it.

2. No, it should be really easy. I can do it for you.

3. No confirmation, just a permanent 301 redirect. People want to get to the page, they will just be annoyed if they are stopped for ads or whatever.

**Comment by Zofz** [comment]
Great - the board had no problem with it being url like ```fsektionen.se/lank/your-fancy-link```.

**Comment by Zofz** [comment]
Implemented in #66. Ready to close this?

**Comment by jforberg** [comment]
Wait for the merge

**Comment by jforberg** [comment]
Also the links will look like

```fsektionen.se/your-fancy-link```

Like a real url shortener. Not the /link/ part

Yes, the hardcoded app routes take precedence and also I have a fancy validator in place that looks through the routes and checks that they don't collide. It's all in the pr.

**Comment by Zofz** [comment]
Yeah, I didn't think of putting it in the end of the routes, really nice 😄

**Comment by davidwessman** [comment]
Closed with #66, good job.
