### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#246]
I'm not completely pleased with how our error handling is handled.

We have been discussing before that it is good practice to make methods fail and raise error when something is wrong, for example #93.
How should we render these errors? And catch them?

I tried to do something a while ago: 
https://github.com/fsek/web/blob/master/app/controllers/application_controller.rb#L17

But I realize that this works very poorly and is not general enough.

What should we do on `AccessDenied`, `RecordInvalid`? 
Any other errors we should catch specifically?

**Comment by jforberg** [comment]
RecordInvalid means a form error. This will have to be handled in the respective action. I actually think your solution is the correct one but it requires the forms to do the right thing also. That is, every form action needs to handle the case of being rendered twice with possibly invalid data. Thus the form elements should inspect their record and present any validation errors. This can be done generally but it's some work to get it right. I have done it in the past and got it mostly right.

AccessDenied is something that you would only get if (1) we messed up in our views or (2) they hacked the url. So a blank screen with some explaining text is an acceptable solution.

**Comment by davidwessman** [comment]
`AccessDenied`is also called by  Cancancan.

**Comment by jforberg** [comment]
...But you should never get to the point where Cancan catches you. Because you should never be presented with any hyperlink which you are not allowed to access.

**Comment by davidwessman** [comment]
Now I see what you mean :)

**Comment by davidwessman** [comment]
What do we do when people need to sign in?
For example if someone want's to rent the car, when should we tell them to sign in to be able to?

**Comment by jforberg** [comment]
"Needs login" should definitely be a different exception than "Not authorized". Not sure if it is.

**Comment by jforberg** [comment]
In this case we could have a public page saying "the section has a car" and "log in to rent it". Then a different page for logged in users with more info?

**Comment by davidwessman** [comment]
We do not have a special error for not-logged-in!

Yeah, right now the *landing page* for rent could handle this :)

**Comment by jforberg** [comment]
I think we should because they are different errors. One is solvable and one is not.

If you are not logged in, you can solve that by logging in.

If you are not authorized it means that you are hacking the app or the app is broken and displaying urls it should not. In neither case it that something you can solve.
