### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#248]
It is time to get our internationalizations going!
A lot of hard-coded strings have been moved to `config/locales`, but now we should start to use it.

# Purpose
Our website should have some of it's content (and perhaps all of it?) in another language.

# To do
- [x] `routes` systemize  the routing
- [x] `switcher` a nice switching-control and handler
- [x] `translation` all the `.yml`-files needs to be translated, any nice way to do this?
- [x] `globalize` implement the ability to translate model-fields, see [Globalize](https://github.com/globalize/globalize)
- [x] Store locale for users (to allow emails and similar to be in right language)

# Specification
## Routes
What I really enjoyed when getting into RoR was the ability to make nice urls and this is the only reason that we have translated routes today.
- How should we do with routes?
- It makes sense to be able to link to a page in a certain language, that `fsektionen.se/about` always should link to an english version of the page. You could add the `:locale`-prefix in the routes: `fsektionen.se/sv/about`, or you could use translated paths: `fsektionen.se/om == swedish version, fsektionen.se/about == english version´
- What do you think?

## Switcher
- Easy switching
- Flags?
- All links should also change - so that it will always link to the same locale

## Translation
- I just worked with PoEdit and stuff before, but havn't used anything for yml

## Globalize
Should be used in:
- Albums
- News
- Notices
- Events
- More?

**Comment by davidwessman** [comment]
Closing #97, because it is kind of counter-productive to work with Internationalisation in Swedish, or somethinng ;)

**Comment by kotrfa** [comment]
For the routes I would personally rather use `:locale` prefix and only for English (so it's not `/sv/about`, but `/about` when Swedish and `/en/about` when in English).

For a switcher I like right top corner. It should be easy to separated it from user authentication links. Since it's going to be only in Swedish and English, I would prefer to have there `English` when the site is in Swedish and `Svenska` when the site is in English. But those are again very subjective choices. But I hate when I need to scroll down all around and search for a language switch. It's even more frustrating when the switch in is current language, so you don't even recognize it. Small flags might help to, but I would be very minimalistic.

**Comment by davidwessman** [comment]
Yeah, since most users will prefer swedish I would agree with the paths.

Yepp, definitely sounds like a good idea. [This](http://htmlstream.com/preview/unify-v1.8/) is our our theme has theirs setup.

Ofcourse, translating would mean a lot of work.
But we could outsource it to people in the guild ;) 

https://www.localeapp.com/
Looks like a cool solution where you put all your translations in a GitHub-repo :)

**Comment by kotrfa** [comment]
Yes, their solution seems also OK (`Languages` button which changes with language). But since I doubt about more than two languages, we could avoid a drop-down menu and have it as a switch.

And this outsourcing idea sounds great. How hard is to set it up?

**Comment by jforberg** [comment]
Google translate should definitely be considered. Even if we translate the app I can tell you the hard part will be making all the content creators submit articles in several languages. The LTH union has tried and failed several times over.

Please, no more offsite services for simple stuff like this.

**Comment by davidwessman** [comment]
How does the Google translate thing work?

**Comment by jforberg** [comment]
Not sure but I know that a lot of people (even the big players) have started using it for translations. When you consider the huge amount of text that some companies have on their websites the cost of translation can be very large. Google translate gives mediocre results at best but it's free!

**Comment by davidwessman** [comment]
https://github.com/glebm/i18n-tasks
I added this gem to check for missing translations, this can also prefill by Google Translate.

**Comment by jforberg** [comment]
Looks great:

> Missing keys only blow up at runtime.
> Keys no longer in use may accumulate and introduce overhead, without you knowing it.

Those are real problems, if this library can mitigate them then that's great.

**Comment by kotrfa** [comment]
I think e.g. [studentlund](http://www.studentlund.se/) use google translate.

**Comment by davidwessman** [comment]
Seems like it!

**Comment by davidwessman** [comment]
http://glebm.github.io/i18n-tasks/

**Comment by davidwessman** [comment]
The board went crazy excited about the ability to localize the page. 
So this should getting some attention after the elections I think.
