### ISSUE TITLE
Normalising tool use: templating and client scripting

### ISSUE THREAD

**Issue by jforberg** [fsek/web#249]
Currently we are mixing tools which I think is unnecessary. For instance we use either HAML or ERB for templating and either coffeescript or javascript for client scripting. We seem to have settled on SCSS for stylesheets which is good.

Since we are starting to do more serious code-review this is starting to become a problem, because code-review depends on being able to understand each other's code.

The tools are all interchangeable as far as I see it and there are few serious technical arguments to be made for using one or ther other. I propose that we just have a vote and select which tools we are to use.

Note that I'm talking about new code. The old code will be refactored when and if we have a reason to.

Please make a post giving your vote in each category. Optionally you can give your reasons for liking that technology and we can have a good old-fashioned holy war about it as well :)

**Comment by jforberg** [comment]
My vote:

Templating: ERB
Client scripting: Javascript

Reasons:
I actually prefer Haml because I think it is easier to read. But this is a project which beginners should work on and all code examples are always in Erb, so that's that.
Javascript because I think the benefits of Coffescript over tastefully coded Javascript are slim at best. And for those benefits you pay a steep price in having to debug compiler output instead of the real code.

**Comment by kotrfa** [comment]
Agree. I was a bit confused by HAML at first (it was what scaffold generated for me), but right after I realized that it's just easily readable version of ERB, I got used to it. Nevertheless, its benefits to ERB are quite similar to CS to JS...

**Comment by davidwessman** [comment]
Templating: ERB 
Client: pure Java (coffee is scary)

The reason that scaffold generates .haml is because we have the `haml-gem`installed, which we need since some views are haml.

For example Permissions, Shortlinks.

@kotrfa Yeah, going .erb would be nice :)

**Comment by jforberg** [comment]
As stated, I don't think you should spend any time rewriting code. What I propose is for new code to use a common toolset.

**Comment by davidwessman** [comment]
This is pretty set :) 
I just wrote it down in the WIKI, should perhaps be in the `readme` or such.
