### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#266]
## MVP (Minimal viable product)
- [x] Check EXIF-info
- [x] Download option (only to be used by admins on demand)
- [ ] ~~Only keep hashes on public files [original filename in the beginning]~~
- [x] Original filename + hash so it is still searchable
- [x] Photographers names
- [x] Display the policy for images
## Further improvements
- [x] Index foreign keys
- [ ] Merge old information
- [x] Background worker for processing
- [x] Reprocess images
- [ ] Categories - for albums and images
- [ ] Tags / Likes
- [ ] Collect JPEG-exif to sort after photo taken
- [ ] Add a static file in every album folder with album info.
- [ ] Add a tooltip after you click the `share`-button (hard to understand that it makes the url-shareable)
- [x] Better links to administrating image, for example removing and such.
- [ ] Ability to request removal of an image

**Comment by jforberg** [comment]
Download option: Fsek photo archive is licensed under Creative Commons. So download does not have to be restricted.

Or did they change this?

**Comment by jforberg** [comment]
Hmm, I guess the CC license was decided in 2010. Anything before that is maybe not public.

Anyway, the old archive system had a download option for all members. Would it be a problem to keep the option? Usually people want to download images of themselves for use on Facebook etc. which seems like a reasonable thing to do.

**Comment by jforberg** [comment]
Aside from that the list looks good I think.

If you get the album up, I can write a migration tool.

**Comment by davidwessman** [comment]
In the policy for images (https://fsektionen.se/dokument/31) it says:
> for handing over images to third party, permission is required from photographer and persons who can be identified on the image

So I think we should restrict the download-option. I can speak to the board as well.

**Comment by davidwessman** [comment]
I checked the EXIF-info and it was intact (atleast on saved original), gonna test it a bit more.

I managed to only hash `thumb`- and `large`-version, but the filename is then referring to the non-hashed path and the versioned images cannot be found. Gonna research this more.

**Comment by davidwessman** [comment]
Would be great if you wrote a migration tool :) 

Could you also list how the old data should be structured? 
Is it tags and comments? Or other things as well?
The storage could be temporary if we want to add it in another format later.

**Comment by jforberg** [comment]
Policy: Ok, then that's good.

Old data: Just open up the database and look around. I haven't looked too much at it but I know that there was a tag system among other things. We could consider if we want to have tags in the new gallery as well.

It was very useful for looking up members in Fsek. It was basically the best member registry we had for several years.

**Comment by davidwessman** [comment]
Yeah - added tags and comments as a future improvement.

Perhaps we can add the old albums later as well? So we can try to finish up what we have.

Would it be okay to change the filenames to `original name` + `md5-hash`+ `.extension` because I couldn't have different names on different versions of the file.

**Comment by davidwessman** [comment]
Authorization:
  We want to be able to limit the visibility of an album.
 1. During Initiation we want to be able to hide albums for new users (perhaps they can be tagged as new or something.
 2. Should the Gallery-page be available to everybody? As a preview? And then require sign in to view?
 3. Right now we have public: true/false, would there be a reason to have it as:
public: :all/:signed_in/:member instead?

Does this sound okay, how could it be implemented?

**Comment by jforberg** [comment]
1. I think this is complicating things. So now you have to be marked as (1) a member and then (2) as a full member after the nollning. This seems like a lot of work. Besides, if they want to know secrets about the nollning the could just look at the Fwiki.

2. There is no reason to show any pictures to non-members. Then our future employers will find us on google drinking lots of cheap beer sitting on a rooftop and nobody wants that. But on the other hand, I think all members should be allowed to see all pictures.

There might be a need to have 2-6 official "press photos" but that could (and probably should) be handled outside the gallery application.

3. IMO you can just remove the column. All pictures should be private to section members but nothing should be secret. Just my opinion.

**Comment by davidwessman** [comment]
Great comments, think everything is done soon.

I want to get every album which does have images.
Havn't found a good way for this.

**Comment by davidwessman** [comment]
@jforberg 
We where talking some about the foreign indexes but I cannot remember what.
Where should we index more? You sad all foreign keys and such.

**Comment by jforberg** [comment]
Foreign keys should be indexed unless there is a reason not to.

http://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys
