### ISSUE TITLE
Projects: new feature

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#268]
After some discussions during preparation for general meeting we came up with the idea of projects with timelines.

For example a timeline for the project of building the new speakers.
As a promotion for starting new projects and get inspired and stuff.

(No rush)

**Comment by jforberg** [comment]
Have you looked at the system TLTH uses?

https://intranet.tlth.se/index.php?menu_display=26

We have been using that for some time and it works quite well for keeping track of stuff that is going on.
