### ISSUE TITLE
Better SMTP?

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#27]
The board would like some kind of web mail interface instead of using the current google-hook-up.

Ideas? Problems?

I looked a bit and think that Roundcube seems nice, also found a guide for Roundcube+Postfix.

Refs:
[Roundcube](http://roundcube.net)
[Postfix+Roundcube](https://rtcamp.com/tutorials/mail/server/postfix-dovecot-ubuntu/)

**Comment by Zofz** [comment]
Would be great to sync it with the Post/Role-system as well! 😄

**Comment by davidwessman** [comment]
Closing this for now.
A dream:
A postfix + dovecot + roundcube solution synced with the user accounts and what posts they have would be awesome!
