### ISSUE TITLE
Guidelines: Date and Time-formats

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#275]
While working at #274 I realized we might need to decide on a default time format.
I thought we can discuss and decide and mark the finished ones with the checkbox.
Then we can move this to the new helper in #274 and perhaps some other implementations, then add how to use it in the Wiki.
- Ideas? 
- What should we do with locales?

# Date
## Single
 - [x] default: `%d %b %Y`
 - [x] long:     `%d %B %Y`
 - [x] short:    `%d %b`

# Time
## Single
 - [x] default: `%H: %M, %d %b %Y`
 - [x] long:     `%H:%M:%S, %d %b %Y`
 - [x] short:    `%H:%M, %d %b `

**Comment by davidwessman** [comment]
Does this seem okay as standard swedish locale?

**Comment by jforberg** [comment]
+1

**Comment by davidwessman** [comment]
Changed the Time-format to use `,` as delimiter.

**Comment by davidwessman** [comment]
https://github.com/fsek/web/wiki/Working-with-Time-and-Dates!
