### ISSUE TITLE
SEO: better titles, descriptions 

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#282]
(Not mainly for showing up in SE-searches, but there is no proper meta information for when you i.e. link to Facebook)

Did an analysis which you probably shouldn't care too much about, but it really shows the health of our SEO.
http://www.analizer.org/82500be0-5781-4c56-94eb-10dd4ababfdb

It could be worth implementing something like https://github.com/kpumuk/meta-tags
or some guidelines for adding meta-information.

Ideas?

## Todo

- [x] Sitemap
- [x] Meta-tags, descriptions

**Comment by jforberg** [comment]
I know nothing about Seo but I guess it could be good.

We already own the search term "f-sektionen", perhaps there are other terms we should like to be top results of?
