### ISSUE TITLE
Email: gmail doesn't like our contact form.

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#289]
We have some issues with the headers in the emails sent from our Contact forms (to @fsektionen.se-emails).

I found a solution for the improper `Message-ID.
http://blog.mailgun.com/tips-tricks-avoiding-gmail-spam-filtering-when-using-ruby-on-rails-action-mailer/

Right now we send the email like:
```
to: guild_member@fsektionen.se,
from: person@contact.com
```
And it is _frowned upon_ by Gmail when the from-domain doesn't not point to the same IP as the message is originating from.

How should we do this? I really like the way that you can instantly reply to the message and you get the persons name and emailadress connected.

I was thinking about the `reply_to` field, could it work to use that?

**Comment by jforberg** [comment]
My suggestion:

From: dirac@fsektionen.se
On-Behalf-Of: johan@forberg.se
Reply-To: johan@forberg.se

**Comment by davidwessman** [comment]
Couldn't find any method for `On-Behalf-Of`, should you add it to the header?

This is how the Header looks now:
```
Date: Thu, 21 Jan 2016 22:55:20 +0100
From: Spindelman <dirac@fsektionen.se>
Reply-To: Hilbert =?UTF-8?B?w4RsZw==?= <hilbert@gmail.com>
To: Spindelman - David <spindelman@fsektionen.se>
Cc: Hilbert =?UTF-8?B?w4RsZw==?= <hilbert@gmail.com>
Message-ID: <5cf82588ffe2c7ab38abcb2b4d83e6b276a92d22613999b87f69f3c50f8f4ee5@fsektionen.se>
Subject: Meddelande skickat via Fsektionen.se
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_56a153c8701f4_bd743ff971467a082695a";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
```

**Comment by jforberg** [comment]
Method: No idea. Can't you just add it to the header?

**Comment by davidwessman** [comment]
The message looks better now, no hard errors in Gmail like before. 
It did still go directly to junk.
Now you can add `dirac@fsektionen.se` as a contact and stuff, perhaps that can help.

**Comment by davidwessman** [comment]
#290 Has addressed some of these errors and it appears to be better.
Not 100% ready to close yet.

**Comment by davidwessman** [comment]
I got contact emails sailing straight through after adding dirac@fsektionen.se to as a contact.
