### ISSUE TITLE
Sort order of upcoming events

### ISSUE THREAD

**Issue by lham** [fsek/web#305]
On the front page I can see the following:

**Kommande evenemang**

    Lördag:  18:00 Skiftesgasque 2016  
    Idag:  18:00 SåS-tack  
    Måndag:  12:15 Info om nollning ...  
    Tisdag:  17:15 Obligatorisk utbi...  

Should they really be sorted in such an arbitrary order? ;)

**Comment by davidwessman** [comment]
Haha no, I just saw that as well.

**Comment by davidwessman** [comment]
@lham Nice to know that you keep an eye out for us 😄

**Comment by lham** [comment]
Of course ;) I'm still subscribing to the mail list and read the comments you guys exchange, even tho I seldom read the code.
