### ISSUE TITLE
Contacts: Avatars when not signed in

### ISSUE THREAD

**Issue by navro** [fsek/web#316]
On the new contacts page you can see the users avatar next to the text, which is very nice! But if you are not signed in, this is replaced with the text 'Avatar'. This should be changed so that i shows

a) The same picture as for users without avatar
or
b) The picture that signed in users see

I would prefer b), but that would probably require that we make avatars public?

**Comment by davidwessman** [comment]
I think b) is okay.
Fail by me for not thinking about the avatar... ;)

**Comment by davidwessman** [comment]
#334
