### ISSUE TITLE
EU Cookie law

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#33]
Rails does save cookies for some things (for example, stay logged in (which might not yet be completely implemented in our Devise config)) and since 2012 there is actually a law that you need to inform users that this happens.

So if I am not completely lost I think we should implement something to show this, and I found a gem:
https://github.com/infinum/cookies_eu
What do you think?
@fsek/admins

**Comment by henrikssn** [comment]
Looks good to me

**Comment by davidwessman** [comment]
It almost took a year!
