### ISSUE TITLE
Mysql: cannot store 4-byte emojis

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#332]
http://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/

Which is apparently an issue. According to this article there should be no problem with migrating?

Could you somehow filter them in rails?

**Comment by navro** [comment]
Oh no :open_mouth:

**Comment by davidwessman** [comment]
Or we change to Postgres (a)

**Comment by navro** [comment]
+1

**Comment by jforberg** [comment]
I prefer postgres for most applications but remember that we still have several legacy applications which need mysql. So we would have to maintain two databases.

My vote is to stay with mysql and tell people to use sensible characters in their posts.

**Comment by jforberg** [comment]
Things like this are exactly why I tend to stay away from mysql otherwise. So we call this character set utf8 but make it support only part of utf8. Because otherwise it wouldn't be confusing enough.

And then of course if we ever encounter a character we don't understand, let's just stop there and ignore the rest of the string. It probably wasn't that important anyway. No need to raise an error, just return ok and leave it at that.

F*** mysql.

**Comment by davidwessman** [comment]
Which Legacy applications do you mean? The wordpress + Postfix?

**Comment by jforberg** [comment]
Postfix can probably work with postgres. I'm thinking of wordpress. Also don't we run some sort of wiki? And vecktorn service?

**Comment by davidwessman** [comment]
WordPress appears to be a bit messy. 
No active wiki as far as I know.

Vecktorn is running on mailchimp

**Comment by navro** [comment]
This problem just got bigger with the launch of the app/group chat function. MySQL will have to be removed as soon as possible, I think we've had enough problems with it. This means that the Farad site has to be moved, but we planned to do this anyway. Postgres it is!

**Comment by navro** [comment]
| Service        | Status  |
| ------------- |:-------------:|
| Rails production/stage      | Can be migrated |
| Postfix (e-mail server)      | Can be migrated |
| Farad (wordpress) | Can **not** be migrated    | 
| Old blog (wordpress) | Not used, can be dropped    | 

So it should be safe to do this when we have moved Farad 😄

**Comment by davidwessman** [comment]
Move without Farad :+1:

**Comment by navro** [comment]
We are now on postgres! 😄
