### ISSUE TITLE
Pages: embed forms, signup forms

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#341]
How can this be done safely?
Should we allow administrators to create pages where an iframe can be rendered?

**Comment by jforberg** [comment]
Although we may not like them, iframes are a fact of life. I once wrote a syncing module for Podio forms. It was not pretty but people still preferred it to the in-house forms.

"Safety" is up to the user. All we can do is make it clear to them that they are giving their personal details to compay X and not to the section. Either that or make something which is so good that they prefer it to Podio.
