### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by jforberg** [fsek/web#350]
It seems we are in general agreement on style except for a few issues. In theory this shouldn't be a problem but since we use hound-ci it will be a problem as our pull requests are filled with increasingly irrelevant comments from mr. hound.

I think we should settle on a style and then configure hound-ci to accept it, so we don't have to deal with his nagging. Or actually I think we should get rid of the hound... but I know you guys like him, so OK.

As I see it there are two points of contention:

### Point B: Space inside of compund literals
Alternatives:
1. ```a = [ 1, 2, 3 ]; b = { 'x' => 1, 'y' => 2, 'z' => 3 }```
2. ```a = [1, 2, 3]; b = {'x' => 1, 'y' => 2, 'z' => 3}```
3. ```a = [1, 2, 3]; b = { 'x' => 1, 'y' => 2, 'z' => 3 }```

### Point A: Hash literal syntax
Alternatives:
1. ```a = { 'a' => 1, :b => 2 }```
2. ```a = { 'a' => 1, b: 2 }```
3. ```a = { 'a': 1, b: 2 }```

I will now give my preferences and you can add yours. Perhaps there are more points or alternatives, please add them in that case.

**Comment by jforberg** [comment]
A: 1. Reason: consistency.
B: 1. Reason: consistency.

**Comment by davidwessman** [comment]
When looking into this I realize I follow most of the https://github.com/bbatsov/ruby-style-guide which is what Rubocop standard configuration is based on.

I do really prefer not using the *hash-rocket* so I added B: 4 and A: 3.
But I can see that the `'x': 1` looks a bit strange and it does not comply with the style guide either.

The Hound is also the main reason that I do now have a way of writing ruby, which is great for anyone new joining as well. I can understand that it is nagging when moving between projects and using different syntaxes.

I would choose:
A: 3
B: 3

On A:3 I could accept using `=>` when having string keys, but always try to use symbols with the `symbol: value` syntax.

**Comment by jforberg** [comment]
What, you can edit other people's comments? And it doesn't even show that it was edited? Come on, github...

Rubocop is good if you need it. I tend to find most of my style errors when reading my patches before submission, most of my hound warnings occur simply because the hound and I disagree.

B:3) I did not know that you could write it like that. That's not very pretty IMO and still doesn't work for hash keys of different types, or when using variable hash keys. So you always need the hashrocket.

Since you write 95% of all code in this project I think it's natural that you get to decide the style. I don't think ```{ 'a': 1 }``` looks nice at all so if we could avoid that I would be happy.

**Comment by davidwessman** [comment]
(I know, it's crazy! Might depend on our team setup though?)

Then I would prefer following the linked ruby-style-guide in these cases:
> Prefer symbols instead of strings as hash keys. [link]
   ```ruby
   # bad   
   hash = { 'one' => 1, 'two' => 2, 'three' => 3 }
   # good
   hash = { one: 1, two: 2, three: 3 }
   ```
   Use the Ruby 1.9 hash literal syntax when your hash keys are symbols. [link]
   ```ruby
   # bad   
   hash = { :one => 1, :two => 2, :three => 3 }
   # good
   hash = { one: 1, two: 2, three: 3 }
   ```
   Don't mix the Ruby 1.9 hash syntax with hash rockets in the same hash literal. When you've got keys that are not symbols stick to the hash rockets syntax. [link]
  ```ruby
  # bad
  { a: 1, 'b' => 2 }
  # good
  { :a => 1, 'b' =>  2 }
  ```

**Comment by jforberg** [comment]
I'm ok with this rule. We can close this.
