### ISSUE TITLE
Validate email for nominations

### ISSUE THREAD

**Issue by navro** [fsek/web#352]
We should validate that `:email ` really is an email address. Many people believe that they can write a stil-id here instead...

**Comment by davidwessman** [comment]
The users are always right...

Email addresses can have almost any formats nowadays.
I did a small PR that should make it harder to do wrong.

**Comment by jforberg** [comment]
+1 for simple validations. It's more or less impossible to write a regex that supports all valid emails.

I usually stick to the very basics and use /@/ as my email regex, I see that you did something only slightly more complicated.
