### ISSUE TITLE
Deployment time: Travis CI

### ISSUE THREAD

**Issue by Zofz** [fsek/web#36]
There are some methods to speed up the Travis testing process, 
some does require special storage of used gems.

Ideas?

Refs:
http://docs.travis-ci.com/user/speeding-up-the-build/
https://coderwall.com/p/x8exja/speed-up-travis-ci-build-preparation-time-by-800

**Comment by henrikssn** [comment]
Our builds are quite fast as it is. I would consider this as low priority :)

**Comment by Zofz** [comment]
Yeah, I managed to change the config a bit, before it was slower.
So until the test base grow, we can close this.
