### ISSUE TITLE
Backup: Database

### ISSUE THREAD

**Issue by Zofz** [fsek/web#38]
Schedule backup of database for ability rollback and restore.
On production it is currently running on mysql.
Anyone know how to do this?
@fsek/admins

**Comment by henrikssn** [comment]
I created a script which backups the database to /root/mysqlbackup every night at 4:00 am.

I'll wait and see if it works before I close this.

**Comment by Zofz** [comment]
Great :)

**Comment by henrikssn** [comment]
root@dirac:/home/erik# ls /root/mysqlbackup/*.gz
    /root/mysqlbackup/database_18-03-2015.sql.gz

**Comment by Zofz** [comment]
Good work 😄

**Comment by jforberg** [comment]
Bra jobbat!

Får man önska ett datumformat som sorterar i ordning? Typ 2015-03-18 ist för 18-03-2015

**Comment by lham** [comment]
+1 på Johans förslag

**Comment by henrikssn** [comment]
Fixat
