### ISSUE TITLE
Tools: Adding categories for tools

### ISSUE THREAD

**Issue by adrianroth10** [fsek/web#451]
Now it's all a mess and it will be hard to find tools if you don't know the exact name of it!

**Comment by davidwessman** [comment]
Perhaps it could work with a searching function based on the descriptions? :)

**Comment by adrianroth10** [comment]
that's true and seems easier to implement!

**Comment by davidwessman** [comment]
Searching would be much better in Postgres though :/

**Comment by adrianroth10** [comment]
what's postgres?

**Comment by davidwessman** [comment]
It is a relational database, today we use MySQL - but we have been thinking about moving to Postgres instead. For example we cannot save 8-byte emojis :( #332

**Comment by adrianroth10** [comment]
yeah I heard about that! So what do you want to say with that? Should I wait with it?

**Comment by davidwessman** [comment]
I think you can start to look at a searching function if you want to 😄 
It can start out basic with some SQL `LIKE`-statements and if we get to Postgres, we can push it further 😄
