### ISSUE TITLE
Rename Post > Position

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#454]

**Comment by jforberg** [comment]
+1 good idea. Mixing languages is a bad thing and English is clearly the language of the business.

**Comment by navro** [comment]
Too many lines to change. David tried, but nobody wanted to check that PR.
I am closing this for now

**Comment by davidwessman** [comment]
I was thinking that you should create controller for `PostUser` instead, since the [`PostController`](https://github.com/fsek/web/blob/master/app/controllers/admin/posts_controller.rb) is terrible.
Perhaps that could be a way to start renaming stuff :)
