### ISSUE TITLE
Inloggning: användarnamn/mejladress

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#5]
Det ska gå att utöka Devise(det gem som hanterar användare) så att man kan logga in med sin mejladress också.
Problemet uppstod då någon försökte logga in med sin mejl, och endast lyckades logga in efter att lösenord återställts - eftersom att då fyller devise automatiskt i användarnamn. 

Står inget i återställningsmejl om att det är användarnamnet som är för inloggning.

**Comment by jforberg** [comment]
Detta är lätt som en plätt i devise. De har till och med skrivit en howto om hur man gör det.

https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

**Comment by davidwessman** [comment]
What do you think about removing the username completely? 
And just use email?

**Comment by davidwessman** [comment]
#262 will close
