### ISSUE TITLE
Photo gallery - Import

### ISSUE THREAD

**Issue by jforberg** [fsek/web#520]
Hi all, it's been some time since I posted here. I just checked the production page and it seems to me that the photo gallery sub-app works well and is now feature-complete to a reasonable degree. This is great news of course.

As you know, we have a huge digital photo archive stretching 20+ years back. At some point we will want to import these to the new gallery.

Here we can discuss the procedure of this import. I specifically present these points:
1. Are we ready for the import now, or is there some feature that we need to implement first?
2. Is the Rails code quick enough to do the import, or do we need to bypass the app and work directly with the database / ImageMagick?
3. There is some metadata in the old database like tags which is not implemented in the new solution. Should we import this data now, even though we can't currently display it?

I'll be happy to help with the import to the extent that my help is required/desired. As a former section photographer and owner of hundreds of the photos in the archive I naturally hold a small personal stake in this.

**Comment by davidwessman** [comment]
Sounds like a great idea 😄 

It would be good to try to find a way to better take care of meta-data. For example for sorting of images. Tags is something that would really drive more active user interaction to the page.
I've been thinking that you could do it without any coordinates and just add an object if the user is in the picture. Or find a way to solve it with coordinates as well.

If we are going to do a lot of image preparation we should probably get some background-workers going, then the web app can handle file upload (or we somehow transfer it via the filesystem on the server) and then just queue up the jobs for letting CarrierWave and ImageMagick do the job.

Based on some of the things in #266 I would answer the questions:

1.  
     - Better handling of meta-data
     - Store album information in a .txt file (so if you look into the storage-folder in the future you can actually know what event it is)
2. If we use background workers
3. Storing the data in the app would be good. Otherwise it will be even tougher to piece together later.

**Comment by davidwessman** [comment]
I got background-workers going now.

However if we want to support multiple uploads, we cannot use a background uploader with our current setup.
Carrierwave have released the `1.0.0.beta` and after that the `carrierwave_backgrounder` will update to support multiple uploads as well.

**Comment by jforberg** [comment]
The import is underway now. Expect the gallery to be a bit broken for a while.

**Comment by davidwessman** [comment]
How? :)

**Comment by jforberg** [comment]
How broken? Very.

**Comment by davidwessman** [comment]
How did you import it? 🙂 

https://fsektionen.se/sidekiq working hard.

Nice job! 🙂

**Comment by jforberg** [comment]
Ah, it's a pretty manual solution. Basically I connect to both the old and the new database, rip the album file structure from the database and then upload it locally though the real interface (carrierwave). There are some limitations (new system doesn't support nested albums etc.) but overall it seems to be working well.

I thought I would have problems with sidekiq (too many open FDs or similar) but it doesn't seem to have any problems at all.

It will take a while to generate all the thumbnails though.

**Comment by jforberg** [comment]
I'll upload the code here when I'm done just for reference.

**Comment by davidwessman** [comment]
Should probably reconfigure Sidekiq to have one queue for gallery and make it a bit lower priority.
Right now email from example the Election would have to wait - I sent some of them manually.

**Comment by jforberg** [comment]
Ok, the import is now done. I think it's mostly correct but there are some remaining issues:

* Obviously, the image processing will take a long time. At least one day and probably more.

* Some of the dates are off, in particular there are a lot of albums under 2000 which should probably be under 2000.

  - A nice solution would be to scan though the exif data in the pictures and set the actual real dates as limits on the album. This will have to wait until the processing is done.

* The caching for the module seems to be broken. I solved it by nuking the cache manually, but this will also have to be done when the processing is done.

* It remains to see how the system performs when it contains 52000 images instead of 4000. In particular, it seemed to have problems with large albums of 1000 images or more. With my current solution, the largest album is only 500 images large, which is of course still quite large.

* There is still some missing data which would be nice to import eventually. Tags is a much requested feature. Also, the current system can't do nested albums but I "solved" this by just flattening the structure.

Let's see how this works and we can get to work with the final adjustments.

**Comment by jforberg** [comment]
Import is now done. I nuked the cache again and everything looks like it should.

So I'm closing this task and opening new for the follow up steps.
