### ISSUE TITLE
Use deliver_now/deliver_later instead of deliver in rent.rb

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#57]
DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job. (called from send_email at /home/travis/build/fsek/web/app/models/rent.rb:123)

**Comment by henrikssn** [comment]
This leads to deprecation warnings for the rails 4.2 migration in #56

**Comment by Zofz** [comment]
Okey. I want to implement some background worker when finishing the gallery but for now we should use ```deliver_now```, will fix it soon.
Is the 4.2 live?

**Comment by henrikssn** [comment]
This was fixed in 09593a and is merged with master
