### ISSUE TITLE
Gallery: download image for non-admin user

### ISSUE THREAD

**Issue by jforberg** [fsek/web#573]
Currently there seems to be no way for a normal user to download the original image.

Maybe the policy has changed, but for images older than say 2013 (so 90% of images in the album) the intention was definitely that users should be able to download them. There was even a decision to release images under a CC license, in 2010 I think.

If this changed later (?), access should in my opinion only be blocked for those images which are affected.

I'm not sure I approve of the watermark in any case. It would be more reasonable to watermark with the photographer's name. In the case where we have forgotten who the photographer was (so 50% of the images), putting any kind of watermark is really pushing it in my opinion.

This problem would of course disappear if we allowed to download the original image. Which, barring any recent decision to limit member's access to the photo archive (did this happen?) I think we should do.

**Comment by davidwessman** [comment]
Sounds reasonable - I would say this is something for the board to handle.

**Comment by jforberg** [comment]
The board can really only change what will happen in the future. For images taken in the past the copyright belongs to the photographer and the section can't retroactively change the terms.

In 2010 we decided to license them under CC BY (I think) with a special exception for the section which could use pictures without limitations. Unless this decision was later reversed, that's what should apply to all images currently in the gallery. For images older than 2010 I think it's reasonable to assume that the photographer would want members of the section to access images.

In this case, changing the access rules was really a technical decision (or non-decision) made by this team. The old album didn't have such restrictions.

**Comment by jforberg** [comment]
This is of course barring any new decision which I don't know about.

**Comment by jforberg** [comment]
Now I found the decision. We removed the CC part.

https://fsektionen.se/dokument/31

So there is actually no mention of members' access to images. My guess is that this was sort of implied since that's how it had always worked at the time.

Then I agree with you that the board should clarify this so that there is no confusion.
