### ISSUE TITLE
Rework registration

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#59]
- [x] Create a user system where everyone can register.
- [x] Require email confirmation
- [ ] Let users confirm their accounts towards medcheck
- [ ] Define guest-user, member, nolla and other roles, perfect together with Cancancan
- [ ] Should be integrated in issue #105 and #109

**Comment by Zofz** [comment]
This adresses #54.

**Comment by henrikssn** [comment]
This could be a great way of moving from the_role to cancan(can)

**Comment by davidwessman** [comment]
This is partly done, still need to define members and such.

**Comment by davidwessman** [comment]
We need a better way to confirm membership, other than that - this is done

**Comment by jforberg** [comment]
How do we currently confirm membership?

In the past, if you signed up using an @student.lu.se mail then you were automatically considered a member. Could a system like this work? (I realise that people from other sections/faculties could register then but would that be a problem?)

**Comment by davidwessman** [comment]
Right now, membership is only manual. Except for all the old accounts which we just gave membership.

I guess using the student-email would work.

**Comment by davidwessman** [comment]
I do not think this is an issue right now.
Especially the way we did it with the Introduction and marking everyone new as members.
