### ISSUE TITLE
Turbolinks/JS: Not loading on full refresh

### ISSUE THREAD

**Issue by navro** [fsek/web#591]
Try to visit https://fsektionen.se/hilbertcafe or https://fsektionen.se/kalender or any page with a select2 controller, and refresh the page. The Javascripts are not loading (calendar, footer, select2, etc).

TL5 issue:
https://github.com/turbolinks/turbolinks/issues/212

**Comment by davidwessman** [comment]
Hm, I guess we could remove the async-loading of Javascripts:
https://github.com/fsek/web/blob/master/app/views/layouts/application.html.erb#L13

 I would prefer this instead of downgrading from TL5.

**Comment by davidwessman** [comment]
I guess we should change our `data-turbolinks-track` as [well](https://github.com/turbolinks/turbolinks#reloading-when-assets-change).
