### ISSUE TITLE
Newsletter: signup abilities for international letter

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#594]
(Found this one at the bottom of my todo-list from long ago...)

There is no way to sign up for the international newsletter, only the Swedish one.

Would be great to support both (perhaps depending on which locale is viewed right now or show both options for any locale.

The sign up links can be found on Mailchimp - perhaps @navro can write them here.

**Comment by navro** [comment]
For the Swedish list:
http://fsektionen.us11.list-manage.com/subscribe?u=b115d5ab658a971e771610695&id=aeb6a02396 (also http://fsektionen.se/vecktorn)

and the English list:
http://fsektionen.us11.list-manage.com/subscribe?u=b115d5ab658a971e771610695&id=3850d20a69
