### ISSUE TITLE
Calendar subscription: write a guide!

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#595]
Right now there is support for iCal-subscriptions, however there have been complaints regarding how to do it.

It would be good to have a guide which shows:
- How to subscribe to iCal with Mac OS and iOS calendar subscriptions,
- How to subscribe with Google Calendar.

`webcal://fsektionen.se/kalender/export.ics` works on some devices, but not for Google Calendar.

**Comment by navro** [comment]
+1

**Comment by navro** [comment]
Fixed in #617 by @jessicalastow
