### ISSUE TITLE
Fix SASS imports

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#62]
In `application.scss` do imports like this http://pivotallabs.com/structure-your-sass-files-with-import/

**Comment by Zofz** [comment]
Are Sprocket deprecated?

**Comment by jforberg** [comment]
Nej men @import är bättre. =require är det man använder om man inte har något bättre. Alltså när språket man jobbar i inte har vettiga namespaces (JS, CS, CSS etc).

Sass har lyckligtvis namespaces och då vill man använda dem.

**Comment by lham** [comment]
Brukar använda @import strukturen andra projekt och det gör livet så mycket lättare. Ytterligare ett knep jag gillar att använda med css/sass är att lägga controller-nmanet som `class` på `<body>` och sedan namespace allt i sass-filerna för varje controller. T.ex.

*views/layouts/application.html.erb*

    <body class="<%= controller_name %>"> ... </body>

*assets/stylesheets/home.css.scss*

    .home {
      p { /* ... */ }
      .specialfx { /* ... */ }
    }

**Comment by davidwessman** [comment]
Nu är all CSS omstrukturerad som:
Imports, alla partials man skapar slänger man i ```app/assets/stylesheets/partials/*``` så laddas de in automatiskt.
Är det viktigt med ordningen någonstans lägger man dem i ```stylesheets``` direkt och lägger in dem med import i ```application.scss```.

Det känns ju rätt nice med att köra med ```controller_name``` faktiskt! 😄

**Comment by davidwessman** [comment]
#222 closed this
Could be worth looking at the <body>-tag with controller_name
