### ISSUE TITLE
Test fail: undefined method `validate_acceptance_of' for RentTest:Class

### ISSUE THREAD

**Issue by jforberg** [fsek/web#65]
NoMethodError: undefined method `validate_acceptance_of' for RentTest:Class
/home/johan/code/fsek/test/models/rent_test.rb:5:in `<class:RentTest>'

@Zofz är skyldigt enligt git blame

**Comment by Zofz** [comment]
Det är jag alldeles säkert, hinner kanske ikväll, annars fredag.

**Comment by Zofz** [comment]
Förresten, vi har väl gått över helt till Rspec? Det där är ju ett gammalt test.
#52 har nog ändrat detta.

**Comment by jforberg** [comment]
@Zofz det kan jag inte svara på. Jag kör rspec för att jag inte kan test::unit men det verkar vara lite 50/50 i det här projektet.

**Comment by Zofz** [comment]
Solved by #70.
