### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#68]
Since we have not used any tests before, we need to start while introducing new features + create some tests for old modules.

@fsek/admins 
What do you think about:
https://gist.github.com/kyletcarlson/6234923
https://gist.github.com/eliotsykes/5b71277b0813fbc0df56

This can be used as a form to create better unit tests for models and controllers.
Not every model needs all the parts, and some needs more custom.

**Comment by jforberg** [comment]
They are taking it too far in my opinion. You should be testing the interface, not just repeating what you wrote in the model. A lot of rails is already very declarative.

Taking the example you linked to. If you have in your model:

```class Developer; validate_presence_of(:favorite_coffee); end```

Then you're not adding very much information by writing a test

```expect(developer).to validate_presence_of(:favorite_coffee)```

As a rule I write a "happy path" test where I pass good information. And then one "sad path" where I cause an error. The key is to test the interface not the internals. If you are poking about the validators (as in the example) you are not testing the interface. 

I actually think I did a resonably good job testing the ShortLink class and controller. You could read those tests and see if you agree with my style:

https://github.com/fsek/web/blob/shortlink/spec/model/short_link_spec.rb
https://github.com/fsek/web/blob/shortlink/spec/controllers/short_links_controller_spec.rb

The amount of testing needed is proportional to the complexity of cases that you need to handle. A simple method does not need to be tested at all IMO if you can see that it is correct just by looking at it.

**Comment by Zofz** [comment]
I do think that our unit tests can be a bit overdone - since much of the code need refactoring and might be a bit more coupled than we want.

When we have improved the code, introduced some proper Integration-tests we can reduce it again.
I like the way you did you tests, very clean and efficient 😄 
But we should (heh) move from ```should```to ```expect``` since the Rspec.should syntax is getting deprecated.

**Comment by jforberg** [comment]
Should is not deprecated. There are no plans to remove it.

http://rspec.info/blog/2013/07/the-plan-for-rspec-3/#what-about-the-old-expectationmock-syntax

You can use either should or expect as you like. I think should is much more clear so I use that one. You just have to configure rspec to allow it.

**Comment by Zofz** [comment]
My fault, it is just a config thing of Rspec then:
```...while we recommend using the new syntax (particularly for new projects)...```
And I think I got the warning the first time running it.

We should add it to our Style guide and discuss it further there 😄 
Can we specify this in Hound? Then -> #71

**Comment by Zofz** [comment]
Another topic.

The helpers for Rspec -  ```rails_helper.rb```and ```spec_helper.rb``` have very similar content.
Do we need both? 
I read something about rails_helper is for the rspec-rails and spec_helper is for normal Rspec.

https://github.com/fsek/web/blob/master/spec/rails_helper.rb
https://github.com/fsek/web/blob/master/spec/spec_helper.rb

**Comment by jforberg** [comment]
"Recommend". They have built rspec with two equivalent syntaxes for whatever reason. Both are supported so go ahead and choose the one you like the best. Everything in ruby can be done in several different ways, for better or worse.

That said, we could decide on a global style if we think that is important. In which case I would be happy to switch to expect if that is the consensus. :)

**Comment by jforberg** [comment]
IDK. They are just files, you can really call them what you want. The reason you might want to have a separate require is that require 'rails_helper' is slow as hell. In general that call takes longer than all your tests combined. But require 'spec_helper' i also very slow so... dunno what would be gained.

**Comment by henrikssn** [comment]
@jforberg I also like the ´foo.should be(bar)´ more than ´expect(foo).to be(bar)`. If it is possible please insert a hound rule to enforce this (Hound uses rubocop for checking ruby files).

**Comment by Zofz** [comment]
We should decide on this soon - and include it in the Hound PR #71

**Comment by davidwessman** [comment]
I think we decided on this and are all working towards 100% - should we close this?

**Comment by henrikssn** [comment]
No, it is not resolved yet. For this issue we should make sure
1. All files have tests
2. Coverage >70%

That is not too hard to achieve.

**Comment by henrikssn** [comment]
Some classes with no tests:
https://codeclimate.com/github/fsek/web/Post
https://codeclimate.com/github/fsek/web/Album
https://codeclimate.com/github/fsek/web/Event
https://codeclimate.com/github/fsek/web/Election
https://codeclimate.com/github/fsek/web/ContactsController
https://codeclimate.com/github/fsek/web/RegistrationsController

**Comment by davidwessman** [comment]
All files do now have tests.
Some are getting better very soon.
