### ISSUE TITLE
Bildgalleri: fillagring

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#7]
Just nu ligger bilderna i public (inte optimalt och borde fixas snarast!)

Man kan använda sig av något som heter sendfile för att få servern att endast leverera filer när vi tillåter det. Detta används nu för Dokumentmodulen, vet inte riktigt hur man implementerar det för att ladda alla bilder samtidigt.

**Comment by Zofz** [comment]
Har löst fillagringen med sendfile på ett bra sätt.
Frågan om visning osv återstår.

**Comment by jforberg** [comment]
Standardlösningen idag tycks vara att ge bilderna långa namn så att det helt enkelt är för svårt att gissa dem. Typ ```SecureRandom.hex 16```. Sedan kan man låtsas som att problemet inte finns.

Då blir det möjligt för någon att skicka länken till en bild och på så vis sprida den. Men det hade ju varit lika möjligt att bara ladda ner bilden, ladda upp på dropbox och sedan sprida den länken. Alltså riktig auth på bilder ger ingen realvinst i säkerhet, det blir bara marginellt enklare att sprida bilder.

**Comment by Zofz** [comment]
Men om sektionsmedlemmar delar bilder kommer vi aldrig undan.
Men vi vill inte att någon ska kunna typ iterera över alla bilder och spara ner dem (jobbigt om vi hashar allting).

På GalleryStorage-branchen har jag gjort det som att varje bild har en /view metod där bilden skickas som inline och då kan vi kolla om folk är användare.

**Comment by jforberg** [comment]
Hur ska du kunna iterera över slumptal?

Om du redan har skrivit accesskontroll så är ju saken klar. Men annars kan du nog lägga din tid på nyttigare saker :)

**Comment by Zofz** [comment]
Min mening blev rörig: hashat går det inte att iterera, hade dagens situation i huvudet.

Jag tyckte att slumptal blev fult och rörigt, provade det i höstas.

Jag vill se hur visningen för ett helt album ser ut på dev, blir det alldeles för jobbigt för servern så får man kanske köra med hash istället.

**Comment by henrikssn** [comment]
Nginx kan serva statiska filer minst 10x snabbare än Passenger. Så vill man ha prestanda är förberg's lösning att föredra.

Nu har vi ju knappt någon trafik så det är väl inte så relevant här :)

**Comment by Zofz** [comment]
Juste, nu har vi ju bytt från apache.
För i Apache så kunde ```send_file``` köras med ```X-send-file```som utnyttjar Apache istället.

Hittar detta på att göra samma sak med Nginx,
http://thedataasylum.com/articles/how-rails-nginx-x-accel-redirect-work-together.html

Vad tycker ni om det?

**Comment by jforberg** [comment]
Erik har rätt, Nginx är minst en storleksordning snabbare än något som måste röra Ruby.

Vanligtvis spelar inte detta någon roll men tänk på att det är flera bilder i ett galleri. Låt säga att du har 32 bilder på varje sida. Varje bild kommer laddas för sig med en egen GET och du måste varje gång kontrollera att (1) användaren finns och (2) användaren har en viss roll.

Så det blir fort långsamt och det helt i onödan. Sedan kanske detta går att göra med en klyftig nginxkonfig och då är det ju fräckt. Men min poäng är att det knappast är ett av de större säkerhetsproblemen i vår app.

**Exempel ur verkligheten:** vi publicerar ju vår secret_token på internet så är all säkerhet vi kan åstadkomma är ju lite påhittad just nu :)

https://github.com/fsek/web/blob/master/config/application.rb#L27

**Comment by davidwessman** [comment]
Not relevant anymore.
