### ISSUE TITLE
User settings start year

### ISSUE THREAD

**Issue by FredrikLastow** [fsek/web#712]
The start year setting goes back to 1954, which is impossible. It should go back to 1961 when Teknisk Fysik was founded by our loving forefathers. You can also pick the coming year as your start year, that is 2019 when it's only 2018.

**Comment by Edde333** [comment]
This is now done for the webpage. Possible start years are now 'nil' and 1961-2018. Still needs to be fixed in the app interface before it can be merged with master.

**Comment by FredrikLastow** [comment]
It's fixed for the app on the user page branch as well. This should only be merged with master after a new version of the app is live with the new changes.

**Comment by Edde333** [comment]
Done
