### ISSUE TITLE
FactoryGirl rent factory fails lint

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#72]
When turning on lint for FactoryGirl the factory `:rent` fails linter with

`* rent - Ett fel uppstod: Användaravtal måste anges, Syfte måste anges (ActiveRecord::RecordInvalid)`

**Comment by Zofz** [comment]
This might be fixed in the #52 PR.
I'll look into it tomorrow.

**Comment by davidwessman** [comment]
@henrikssn I lost track of branches now - but is this fixed on master?

**Comment by henrikssn** [comment]
It is not.

https://github.com/fsek/web/blob/master/spec/support/factory_girl.rb

**Comment by davidwessman** [comment]
Okay, good. Should be done in #87, perhaps I can get this ready to merge tonight.

**Comment by davidwessman** [comment]
Closed.
