### ISSUE TITLE
Bildgalleri: mobilvänligt

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#8]
Bytte vy för ett tag sedan för att det blev snyggt på datorn och det var efterfrågat av några.

Dock så fungerade det senare inte alls som det skulle på mindre skärmar - vi behöver en ny lösning eller lägga till ett mobilalternativ.

**Comment by Zofz** [comment]
http://tech.pro/tutorial/2049/how-to-use-rails-41-actionpack-variants
Är det värt att göra en mobilversion som kanske kör full-screen istället?

**Comment by jforberg** [comment]
Min erfarenhet är att det oftast går att designa en sida som passar alla devices. Vi kör ju bootstrap där man kan speca olika storlekar och beteende för olika skärmstorlekar.

Om inte annat har du alltid Javascript som är mer kraftfullt än något du kan göra i views.

Vad exakt är det för problem du har?

**Comment by Zofz** [comment]
Det är lite efterfrågat att ha både en översiktlig vy och någon form av fullscreen view.
Den översiktliga vy med plats för t.ex. taggar och liknande skulle nog fungera bra på mobiler också.
Har dessvärre inte hittat något jättebra färdigt JS-galleri som fungerar bra.
