### ISSUE TITLE
New fancy build/deploy solution

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#82]
So here is our new fancy build/deploy solution.

1. Travis CI builds and tests all commits on master and dev branches.
2. If success then [Samson](http://samson.fsektionen.se) automatically deploys the commit.

Samson is a web interface to the well-proven capistrano solution.

Try it and come with feedback! :)

**Comment by henrikssn** [comment]
One more thing:
We run both samson/nginx under the deploy user and the two branches have their home directories at
dev: /home/deploy/dev/current
master: /home/deploy/dev/production

`current` is a symlink to the latest release.

**Comment by Zofz** [comment]
So if I now pushed to master - do I need to deploy?

**Comment by Zofz** [comment]
```Merged```with master.

**Comment by henrikssn** [comment]
Nope, Samson deploys your PR automatically if all tests passes.

**Comment by Zofz** [comment]
So if I do a PR and merge it too 
 - master > Samson will deploy to Production.
 - dev      > Samson will deploy to Development

How to do to reset Development? (If it is currently old or very different?)

**Comment by henrikssn** [comment]
Yes.

    git checkout dev
    git reset --hard <commit-id>
    git push -f

**Don't** do this for production. This is only allowed on the dev server :)

**Comment by Zofz** [comment]
For dev, definitely. But does this still use a deploy for this or is it done with the Githook?

**Comment by henrikssn** [comment]
Dev is using the same deploy pipeline as production does. So if bundle/migrations/assets fail then it will stop and scream at you :)

It takes a few mins until it deploys as it waits for travis results. See progress here: http://samson.fsektionen.se/projects/web/stages/dev

**Comment by davidwessman** [comment]
#98
