### ISSUE TITLE
Migration errors

### ISSUE THREAD

**Issue by Zofz** [fsek/web#85]
#74 raises:
```Looks like the migrations on master are broken. It complains about access_code already being in the database. Can you see if you can fix it?```

http://samson.fsektionen.se/projects/web/deploys/29 

So, the migration has the number 41, and on our master branch we have ran up to 44.
But when deploying the state of the database might not be the same, which leads to this migration running twice.

The cause might be som faulty merge from before, but I do not know a neat way to solve it.
My best idea so far is to change it's migration number to something lower.

What would you do? @fsek/admins

**Comment by henrikssn** [comment]
This has happened because someone have changed the numbering on a migration which rake now tried to run twice. I will try to fix this tomorrow.

**Comment by henrikssn** [comment]
Finally fixed this. We need to be more careful when we get merge conflicts in the schema. Never ever change the migration number of a migration, that breaks all kinds of stuff.
