### ISSUE TITLE
Form-builder

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#86]
We do have a lot of similar forms all over the site, what is your opinion on working with for example SimpleForm instead? Could be able to dry up some things, make certain UI-elements easier and the unified design easier.

Ideas or comments?
@lham you have been working SkyForms on your document-branch right? 
What do you think about those?

Ref:
https://github.com/plataformatec/simple_form

**Comment by jforberg** [comment]
Have tried it but I didn't like it. Don't remember why :) Try it out and see if it works.

Having a custom form builder is a very good thing, regardless of whether it subclasses simpleform or standard ActionView::FormBuilder. Then you can do really cool stuff like displaying errors next to the form element.

**Comment by Zofz** [comment]
Building a nice unified Form-builder would be nice 😄 
Anyone who feel like drawing it up can create a branch.

**Comment by jforberg** [comment]
Another question is whether we should use JS validation. It can save performance and make the app more responsive. But on the other hand it means we have to validate everything twice and ensure that the validations work exactly the same.

I usually don't bother with JS validations except for forms with a lot of traffic or where the database operation is very expensive (at work I had a CRM system where queries took 500-1000 ms and I had to do like 5 per request. JS validations check).

**Comment by lham** [comment]
Jag har byggt en form builder för som passar vår layout i dokument-branchen.

**Comment by henrikssn** [comment]
*on the other hand it means we have to validate everything twice and ensure that the validations work exactly the same.*

This is probably going to be a pain so I would say rely on model validations.

**Comment by jforberg** [comment]
Something you really need (but don't realise that you do until you have it) is automatic error presentation in forms. This is built into ASP.NET (Microsoft Rails) and it rocks.

With a custom form builder it is easy to do in rails as well. This means two things:

* Errors are handled implicitly for 90% of cases, the form builder looks into the resource object error method and presents errors next to the respective fields.

* You can reflect on the resource object and check which validators are registered. An example of where this would be good is marking REQUIRED fields automatically based on which PresenceValidators are registered.

It's not hard to do, I can fix us up.

**Comment by Zofz** [comment]
Would love this!
I agree with using model validations and then error presentation instead of JS-validation.

@jforberg: ```Microsoft Rails``` - lovely ;) 

@lham This?
https://github.com/fsek/web/blob/documents/app/helpers/standard_form_builder.rb
Kind of hard code to get without trying it out, but something like this would be great.
Perhaps @lham and @jforberg can collaborate on an example? 😄

**Comment by jforberg** [comment]
@lham has already done what I suggested :) even the _id hack.

lham pls.

**Comment by lham** [comment]
@jforberg Jag hade byggt en egen, men sen tyckte jag din var något snyggare så jag klippte den rakt av ;)

@Zofz Japp, den är rätt grötig, det kan jag hålla med om.
Nu räcker det att göra forms som här t.ex.
    
    <%= standard_form_for @document do |f| %>
      <% blank = 'Välj dokumentsamling' %>
      <% opts = [blank] + DocumentGroup.all.map {|t| [t.name, t.id]} %>
      <% selected = @document.document_group_id || blank %>
      <%= f.select(:document_group_id, options_for_select(opts, selected: selected, disabled: blank), label: 'Dokumentsamling') %>

      <%= f.text_field :title, placeholder: 'Visat filnamn', label: 'Visat filnamn', help: 'Det du vill att andra ska se när filen länkas.' %>
  
      <%= f.date_field :production_date, label: 'Skapat datum', help: 'Exempelvis datum då dokumentet antogs av ett möte.' %>
      <%= f.date_field :revision_date, label: 'Reviderat datum', help: 'Exempelvis datum då dokumentet reviderades av ett möte.' %>

      <%= f.check_box :public, placeholder: 'Publik dokument (syns för icke-medlemmar)?', section: false%>
      <%= f.check_box :hidden, placeholder: 'Dolt dokument (syns endast för användare med rättigheter)?' %>
    
     %>

så genereras fel, hjälptext, form och label för varje fält.

**Comment by jforberg** [comment]
@lham föredömligt.

Jag vill dock slå ett slag för metoden ``collection_select``. Den är den enda selecthelpern som konsekvent fungerar för mig. Den är dock helt ekvivalent det du gör, lite mer kompakt bara.

```
f.collection_select :document_group_id, DocumentGroup.all, :id, :name,
    :prompt => 'Välj dokumentsamling'
```

Det fina med collection_select är att den själv listar ut vilken som ska vara **selected**, vilket ofta är det som knölar till det.

**Comment by Zofz** [comment]
Snyggt!

**Comment by davidwessman** [comment]
Can we get this into production? 
Is #53 ready?

**Comment by jforberg** [comment]
Do it but keep the branch and issue alive... I have some more things I want to automate.

**Comment by jforberg** [comment]
@lham What is the status on that branch? http://github.com/fsek/documents. I'd like to start using the form builder, should I just copy-paste it into master?

**Comment by davidwessman** [comment]
I have started using the simple_form gem because I was so tired of changing the forms.
But I'm definitely up for using our own custom one if you prepare it 😄

**Comment by jforberg** [comment]
@davidwessman Well, that's OK. One doesn't rule out the other.

**Comment by davidwessman** [comment]
The error handling was the main reason I installed it, and that works like a charm.

Much is handled automagically, but you can also specify settings.

f.input :attribute, as: :datetime_picker

Is for example a special input from another gem which gives a nice picker for datetime.

**Comment by davidwessman** [comment]
Not sure about scrolling btw, that might need some work!

**Comment by davidwessman** [comment]
Closing this for now, since we are using SimpleForm.
