### ISSUE TITLE
Startsidan:

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#9]
Lägga till en modell som heter "Notis" det är som en nyhet fast mer statiska, dessa ska ha egenskaper som: plats: (startsida), ordning, visningstid(visas mellan två datum), bild, rubrik, text.
En "col-md-7" kan vara lagom i storlek på framsidan.

Nyhetskolumn liknande den som finns idag, lite bredare

Eventlista: en liten rad precis under bilden (som borde bli en slider igen), kort beskrivning av kommande event.

FNU vill kanske ha något(sponsorer eller så) som borde uppdateras också.

**Comment by Zofz** [comment]
```Notis``` implemented.

**Comment by davidwessman** [comment]
A list of `Events` implemented. FNU didn't want to show their sponsors
