### ISSUE TITLE
Use the bang methods save!, create!, update!, destroy!

### ISSUE THREAD

**Issue by jforberg** [fsek/web#93]
Always use the bang methods on AR objects unless you have a reason not to. Even then, use the bang methods.

I found this code in master:

```
after_create :create_profile_for_user

def create_profile_for_user
  Profile.create(user: self)
end
```

What does this do? It tries to create a profile, silently ignoring any validation errors and then throws away the reference to the only object that has information about the error. Not what you want.

Instead, make it a habit to use the save!, create!, update!, destroy! methods and explicitly catch the exception if that is what you want to do. The exception you want is usually ```ActiveRecord::RecordInvalid```.

Or just let the exception pass to the controller where ApplicationController will do the right thing automatically for you (as of branch cancan https://github.com/fsek/web/blob/cancan/app/controllers/application_controller.rb#L14)

Have a nice day
/Your friendy best-practices PSA guy

**Comment by davidwessman** [comment]
Hmm, I tried this on my branch, but it does not try to render the right action.
How is the action specified?

**Comment by davidwessman** [comment]
Move to Wiki:
https://github.com/fsek/web/wiki/Use-the-bang-methods-save!,-create!,-update!,-destroy!

**Comment by jforberg** [comment]
@davidwessman Activerecord has nothing to do with actions... Or what did you mean?

**Comment by davidwessman** [comment]
I do not remember exactly but I couldn't get the redirect/render to be right in my tests.
Gonna try it again.

**Comment by jforberg** [comment]
Oh sorry now I get it.

You're right and it's actually a bit hard to figure out which action the user is coming from. I did a clever solution (or so I thought) but I'm not surprised it broke.

For now, you can just code out the special cases like ``case action_name; when :create; render :new; end``. Then we can figure out a nicer solution later.
