### ISSUE TITLE
API for song book with chanting songs

### ISSUE THREAD

**Issue by olofenglund96** [fsek/web#951]
The fös wants some chanting songs which will be linked to a suitable category. 
- [x] Finish implementing song categories
- [x] Fix an API endpoint to fetch songs linked to a specific category
- [x] Talk to someone to fix the app

**Comment by FredrikLastow** [comment]
Here are the chants we got from the fös:
[Kampsånger.pdf](https://github.com/fsek/web/files/3496752/Kampsanger.pdf)
