### ISSUE TITLE
Internationalisering

### ISSUE THREAD

**Issue by jforberg** [fsek/web#97]
Som ni kommer märka finns det alltid en sak till man behöver oroa sig när det gäller Rails. Nu har vi kommit till nästa sak: Internationalisering (i18n) och lokalisering (l10n).

**Såhär är det:** Om man vill kunna ha sin app på olika språk, så får man inte hårdkoda någon språkad text någonstans. Ingen. Inte i viewar, inte i kontroller. Allt måste gå via en metod som heter ``I18n.t`` och som slår upp ord från rätt språk på nycklar i de filer som ligger i ``config/locales``. Det är ett ok system, formulären slår upp sina ord automatiskt men det innebär dock att alla hårdkodade textsträngar behöver flyttas till YAML-filer.

Av princip gör jag alltid mina egna projekt internationaliserade även om jag inte tror att det kommer behövas. Men vi har hårdkodat allt vilket är helt förståeligt eftersom det (återigen) är precis så de lär ut det.

Vill vi internationalisera vår app? Om vi inte vill är det helt ok, då kan vi fortsätta hårdkoda strängar. Men det kommer blir tuffare om någon i framtiden (typ sektionsmöte eller liknande) kommer på att vi måste stödja engelska. Vilket är precis vad som har hänt uppe på TLTH.

Något att fundera på även om jag tycker att vi har viktigare saker för oss just nu.

**Comment by Zofz** [comment]
Det är mycket jobb att göra om allt, men det blir också mycket lättare att vara konsekvent.
Jag tycker att det är bra att internationalisera allt man skriver, i alla fall det som används i controllers och liknande.

**Comment by henrikssn** [comment]
+1

**Comment by davidwessman** [comment]
https://github.com/globalize/globalize
Om vi vill översätta objekt också, t.ex. ett Sektionsval.

**Comment by jforberg** [comment]
@davidwessman Har inte kollat på globalize, det är säkert fett. Men just översätta objekt kan man göra i vanliga Rails också.

```Sektionsval.model_name.human :count => x```

**Comment by davidwessman** [comment]
@jforberg 
Var inte tydlig där: man sparar ett objekts attribut i olika språk. 
Kolla på det - verkar fett tycker jag 😄

**Comment by henrikssn** [comment]
Jag har tidiare jobbat med ett system som använder engelskan som nycklar och sedan översätter till andra system från denna (om översättning finns, annars defaultar den till engelska). Det fina är att man kan skriva kod först och översättning senare. Tyvärr var inte det systemet open-source.

Ex:

    puts t('This is a great idea')

Räcker för att skriva ut det på den engelska hemsidan och vill man ha en svensk översättning så får man även skapa en översättning i YAML-filen (vilket inte behövs om endast en engelsk önskas).

Skulle det gå att modda i18n för att funka såhär? Det skulle krävas minimal ansträngning för att omsluta alla strängar med t().

**Comment by davidwessman** [comment]
Hamnar 'This is a great idea' som key i YAML-filen?

**Comment by henrikssn** [comment]
Precis, man använder den engelska texten som nyckel.

**Comment by henrikssn** [comment]
Tror inte det skulle vara så svårt att fixa:
http://guides.rubyonrails.org/i18n.html#using-different-exception-handlers

Vad tror du @jforberg ?

**Comment by jforberg** [comment]
Låter bra. Jag har jobbat med två olika system, "nycklar" och engelska strängar. Engelska strängar är trevligare.

Gäller dock att tänka på att många translations går på objekt och fält istället för strängar. Om man är lite smart så behöver man inte koda så många direkta strängar.
