### ISSUE TITLE
Deploy model

### ISSUE THREAD

**Issue by henrikssn** [fsek/web#98]
Sit down and decide on a model then write down a nice and thorough explanation that we can have in the Readme. Do it like a pull request on the Readme then we can all comment.

I do think we need to sort this out now, before we get new people on the team and have to explain how our working model looks.

**Comment by Zofz** [comment]
Sounds good 😄 Will look at it more tomorrow.

**Comment by davidwessman** [comment]
What do I need to do to deploy my commit? 
Do I still 'draft a new release'?
@henrikssn

**Comment by henrikssn** [comment]
It deploys automatically if tests pass on travis

**Comment by davidwessman** [comment]
Okay, where do I see it running now?

**Comment by henrikssn** [comment]
https://travis-ci.org/fsek/web/branches

When the commit on master passes then samson creates a new release and deploys it.

**Comment by davidwessman** [comment]
Should be moved to a Wiki as well? #119

**Comment by henrikssn** [comment]
@davidwessman You can move this to the wiki and then close

**Comment by davidwessman** [comment]
@henrikssn Can you draft up the wiki on Deploy and then close?
https://github.com/fsek/web/wiki/Deploy-solution

**Comment by henrikssn** [comment]
Done

**Comment by davidwessman** [comment]
:+1:
