### ISSUE TITLE
Add FARAD tab to "We offer" page

### ISSUE THREAD

**Issue by davidkrantz** [fsek/web#983]
The project leader of FARAD 2020 want us to add another tab called "FARAD" to the "We offer" page with the following text [farad.txt](https://github.com/fsek/web/files/3685359/farad.txt). The links and email addresses should be clickable.

**Comment by lucianolima00** [comment]
I'd like to do this issue

**Comment by FredrikLastow** [comment]
@lucianolima00 Go ahead! Just make a PR when you're done and we'll review it. Are you a member in FARAD?

**Comment by lucianolima00** [comment]
@FredrikLastow I needed to put `www.` on the link to the auto_link get it. If there's a problem, I'll try another way to do it
